## rules.yaml
briefing = LANDCOM 16 HQS.
    TOP SECRET.
    TO: FIELD COMMANDER A9
    
    CONGRATULATIONS. CAPTURING TECH CENTERS HAS REVEALED AN UNDERGROUND WEAPONS FACILITY. PLACE EXPLOSIVE CHARGES ON ALL GENERATORS. RESULTING EXPOSIONS SHOULD DESTROY FACILITY.
    GET OUT BEFORE NERVE GAS IS USED.
    
    TRANSMISSION ENDS.
