## ingame-debug.yaml
label-debug-panel-title = 作弊
checkbox-debug-panel-instant-build = 即时建造速度
checkbox-debug-panel-enable-tech = 建造所有东西
checkbox-debug-panel-build-anywhere = 任意位置建造
checkbox-debug-panel-unlimited-power = 无限电力
checkbox-debug-panel-instant-charge = 即时充能
checkbox-debug-panel-disable-visibility-checks = 禁用视野检查
button-debug-panel-give-cash = 给予 $20,000
button-debug-panel-give-cash-all = 给所有人金钱
button-debug-panel-heal-selected = 治疗选中单位
button-debug-panel-dispose-selected = 销毁选中单位
button-debug-panel-grow-resources = 增长资源
button-debug-panel-kill-selected = 杀死选中单位
button-debug-panel-clear-shroud = 清除战争迷雾
button-debug-panel-reset-shroud = 重置战争迷雾
button-debug-panel-level-up = 升级
button-debug-panel-player-experience = 玩家经验
label-debug-panel-selection-title = 选择
label-debug-panel-visualizations-title = 可视化
checkbox-debug-panel-show-unit-paths = 显示单位路径
checkbox-debug-panel-show-customterrain-overlay = 显示自定义地形
checkbox-debug-panel-show-actor-tags = 显示角色标签
checkbox-debug-panel-show-combatoverlay = 显示战斗几何
checkbox-debug-panel-show-geometry = 显示渲染几何
checkbox-debug-panel-show-terrain-overlay = 显示地形几何
checkbox-debug-panel-show-celltrigger-overlay = 显示单元格触发器
checkbox-debug-panel-show-actormap-overlay = 显示角色地图
checkbox-debug-panel-show-screenmap = 显示屏幕地图
checkbox-debug-panel-show-hpf-overlay = 显示 HPF 覆盖层
