objective-failed = Задание провалено
objective-completed = Задание выполнено
primary = Основное
secondary = Дополнительное
new-primary-objective = Новое основное задание
new-secondary-objective = Новое второстепенное задание
destroy-obelisk-sams = Уничтожьте установки ПВО, защищающие Обелиск.
destroy-obelisk = Уничтожьте Обелиск.
destroy-biotech = Уничтожьте биотехнологическую лабораторию.
destroy-sams = Уничтожьте установки ПВО, чтобы получить поддержку с воздуха.
investigate-village = Исследуйте ближайшую деревню и соберите данные о странной активности
reach-village = Доберитесь до деревни.
kill-creatures = Убейте всех существ в этом районе.
establish-beachhead = Займите плацдарм
eliminate-nod = Уничтожьте все силы Нод в этом районе.
capture-refinery = Захватите обогатитель тиберия.
battlefield-control = Контроль поля боя
apcs-left = Отряды БТР в резерве: { $apcs }
retrieve-rods = прутьями
eliminate-reinforcements = Уничтожьте { $kills } отрядов Нод
defend-bialystok = Защитите Белосток
find-gdi-base = Найдите базу ГСБ.
destroy-nod-building = Уничтожьте ******** Нод.
destroy-nod = Уничтожьте оставшиеся здания и войска Нод.
construct-base = Постройте все доступные здания.
repair-base-vehicles = Отремонтируйте базу ГСБ и технику.
destroy-nod-force = Уничтожьте ударный отряд Нод.
protect-mobius = Защитите доктора Мебиуса
protect-hospital = Защитите госпиталь.
keep-civilians-alive = Не допустите гибели мирных жителей
destroy-nod-bases = Уничтожьте базы Нод.
destroy-nod-bunkers = Уничтожьте бункеры Нод, чтобы конвой Картера
    мог безопасно пройти.
convoy-passed-partly = Часть конвоя Картера прошла!
destroy-gdi-troops-area = Уничтожьте все войска ГСБ в этом районе.
kill-nikoomba = Убейте Никумбу.
destroy-village = Уничтожьте деревню.
destroy-gdi-units = Уничтожьте все войска ГСБ.
build-base = Постройте базу.
destroy-gdi-base = Уничтожьте базу ГСБ.
capture-prison = Возьмите под контроль тюрьму
destroy-gdi-forces = Уничтожьте все силы ГСБ.
destroy-village-kill-civilians = Уничтожьте деревню и убейте всех гражданских.
kill-gdi-units = Убейте все войска ГСБ в этом районе.
protect-nod-supporters = Защитите гражданских
kill-gdi-supporters = Убейте всех гражданских, поддерживающих ГСБ.
build-sams = Постройте { $sams } ПВО, чтобы отразить атаки бомбардировщиков ГСБ.
steal-nuclear-detonator = Украдите ядерный детонатор ГСБ.
move-to-evacuation-point = Двигайтесь к точке эвакуации.
destroy-gdi-supporter-houses = Уничтожьте дома сторонников ГСБ
    в деревне.
capture-barracks-factory-conyard = Захватите казармы, военный завод и
    сборочный цех.
find-nod-base = Найдите базу Нод.
eliminate-gdi-forces = Уничтожьте все силы ГСБ в этом районе.
capture-gdi-helipad = Захватите вертолетную площадку ГСБ.
do-not-capture-or-destroy = Не захватывайте и не разрушайте любые другие
    главные здания ГСБ.
orca-wreak-havoc = Используйте «Орку» ГСБ, чтобы посеять хаос в деревне.
distract-guards = Отвлеките охрану, атаковав
    главный вход своей техникой.
capture-gdi-outpost = Захватите аванпост ГСБ.
locate-nod-base = Найдите базу Нод
secure-first-landing-zone = Обезопасьте первую зону высадки.
secure-second-landing-zone = Обезопасьте вторую зону высадки.
kill-gdi-scientist = Убейте ученого ГСБ.
destroy-tech-center = Уничтожьте Исследовательскую базу ГСБ.
destroy-capture-warfactory = Уничтожьте или захватите Военный завод.
destroy-mammoth-tanks = Уничтожьте Мамонт-танки на Исследовательской базе.
keep-commando-alive = Сохраните жизнь вашему коммандос.
nod-soldier = Солдат Нод
take-civilians-money-crates = Найдите все деньги гражданских; им они больше не понадобятся.
quickly-destroy-ion-cannon = Отключите Ионное орудие ГСБ, прежде чем оно выстрелит дважды.
civilians-running = Эй, эти гражданские... куда это они направляются?
destroy-ion-cannon-advice = Не позволяйте им воспользоваться ионной пушкой
village-destruction-warning = Будьте осторожны, командир. ГСБ не будут сидеть сложа руки, пока мы сжигаем всю деревню.
destroy-gdi-bio-centers = Уничтожьте биоцентры ГСБ.
keep-all-other-structures = Сохраните все остальные сооружения в целости
kill-every-villager-in-area = Убейте каждого жителя деревни в этом районе.
careless-gdi-experiments-killed = Неосторожные эксперименты ГСБ убили этих жителей.
villagers-must-not-live = не должны дожить до того, чтобы опровергнуть
clear-path = Отразите засаду и расчистите путь для нашего МСЦ.
recover-old-base = Захватите Строительный двор на нашем разведывательном посту, чтобы восстановить контроль.
air-strikes-intel-report = Авиаудары Нод направляются из Центра связи на северо-западе. Его захват может дать нам полезную информацию.
capture-nod-communications-center = Захватите Центр связи Нод на северо-западе.
communications-center-captured-sams-located = Наши инженеры обнаружили установки ПВО Нод. Они также обезвредили необычную ловушку на Строительном дворе на юге.
