#!/bin/bash
# Copyright 2007,2009,2010 Chris Forbes, Robert Pepperell, Matthew Bowra-Dean, Paul Chote, Alli Witheford.
# This file is part of OpenRA.
# 
#  OpenRA is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
# 
#  OpenRA is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with OpenRA.  If not, see <http://www.gnu.org/licenses/>.
#

# Internal options
RESOURCES_PATH=`pwd`/../Resources

# Display an error to the user and exit
# args:
#    $1: title
#    $2: message

`/usr/bin/osascript << EOT
	tell application "Finder" 
		activate
		display dialog "${2}\n\nSupport is available in our irc channel irc.freenode.net #openra." \
		buttons "Quit" \
		default button 1 \
		with title "${1}" \
		with icon alias (POSIX file "$RESOURCES_PATH/OpenRA.icns")
		activate
		end tell
EOT`
