## rules.yaml
briefing = LANDCOM 66 HQS.
    TOP SECRET.
    TO: FIELD COMMANDER A34
    
    SOVIETS HAVE LAUNCHED HEAVY ATTACKS ON OUR POSITION.
     SURVIVE AND HOLD THE BASE UNTIL OUR FRENCH ALLIES ARRIVE.
    
    CONFIRMATION CODE 5593.
    
    TRANSMISSION ENDS.
