NextProductionTab: PAGEDOWN
	Description: Next tab
	Types: Production

PreviousProductionTab: PAGEUP
	Description: Previous tab
	Types: Production

CycleProductionBuildings: TAB
	Description: Next facility
	Types: Production

ProductionTypeBuilding: E
	Description: Building Tab
	Types: Production

ProductionTypeDefense: R
	Description: Defense Tab
	Types: Production

ProductionTypeInfantry: T
	Description: Infantry Tab
	Types: Production

ProductionTypeVehicle: Y
	Description: Vehicle Tab
	Types: Production

ProductionTypeAircraft: U
	Description: Aircraft Tab
	Types: Production

ProductionTypeNaval: I
	Description: Naval Tab 
	Types: Production

ProductionTypeTank: I
	Description: Tank Tab
	Types: Production

ProductionTypeMerchant: O
	Description: Starport Tab
	Types: Production

ProductionTypeUpgrade: R
	Description: Upgrade Tab
	Types: Production

Production01: F1
	Description: Slot 01
	Types: Production

Production02: F2
	Description: Slot 02
	Types: Production

Production03: F3
	Description: Slot 03
	Types: Production

Production04: F4
	Description: Slot 04
	Types: Production

Production05: F5
	Description: Slot 05
	Types: Production

Production06: F6
	Description: Slot 06
	Types: Production

Production07: F7
	Description: Slot 07
	Types: Production

Production08: F8
	Description: Slot 08
	Types: Production

Production09: F9
	Description: Slot 09
	Types: Production

Production10: F10
	Description: Slot 10
	Types: Production

Production11: F11
	Description: Slot 11
	Types: Production

Production12: F12
	Description: Slot 12
	Types: Production

Production13: F1 CTRL
	Description: Slot 13
	Types: Production

Production14: F2 CTRL
	Description: Slot 14
	Types: Production

Production15: F3 CTRL
	Description: Slot 15
	Types: Production

Production16: F4 CTRL
	Description: Slot 16
	Types: Production

Production17: F5 CTRL
	Description: Slot 17
	Types: Production

Production18: F6 CTRL
	Description: Slot 18
	Types: Production

Production19: F7 CTRL
	Description: Slot 19
	Types: Production

Production20: F8 CTRL
	Description: Slot 20
	Types: Production

Production21: F9 CTRL
	Description: Slot 21
	Types: Production

Production22: F10 CTRL
	Description: Slot 22
	Types: Production

Production23: F11 CTRL
	Description: Slot 23
	Types: Production

Production24: F12 CTRL
	Description: Slot 24
	Types: Production
