CycleProductionBuildings: TAB
	Description: Next facility
	Types: Production

Production01: F1
	Description: Slot 01
	Types: ProductionSlot

Production02: F2
	Description: Slot 02
	Types: ProductionSlot

Production03: F3
	Description: Slot 03
	Types: ProductionSlot

Production04: F4
	Description: Slot 04
	Types: ProductionSlot

Production05: F5
	Description: Slot 05
	Types: ProductionSlot

Production06: F6
	Description: Slot 06
	Types: ProductionSlot

Production07: F7
	Description: Slot 07
	Types: ProductionSlot

Production08: F8
	Description: Slot 08
	Types: ProductionSlot

Production09: F9
	Description: Slot 09
	Types: ProductionSlot

Production10: F10
	Description: Slot 10
	Types: ProductionSlot

Production11: F11
	Description: Slot 11
	Types: ProductionSlot

Production12: F12
	Description: Slot 12
	Types: ProductionSlot

Production13: F1 CTRL
	Description: Slot 13
	Types: ProductionSlot

Production14: F2 CTRL
	Description: Slot 14
	Types: ProductionSlot

Production15: F3 CTRL
	Description: Slot 15
	Types: ProductionSlot

Production16: F4 CTRL
	Description: Slot 16
	Types: ProductionSlot

Production17: F5 CTRL
	Description: Slot 17
	Types: ProductionSlot

Production18: F6 CTRL
	Description: Slot 18
	Types: ProductionSlot

Production19: F7 CTRL
	Description: Slot 19
	Types: ProductionSlot

Production20: F8 CTRL
	Description: Slot 20
	Types: ProductionSlot

Production21: F9 CTRL
	Description: Slot 21
	Types: ProductionSlot

Production22: F10 CTRL
	Description: Slot 22
	Types: ProductionSlot

Production23: F11 CTRL
	Description: Slot 23
	Types: ProductionSlot

Production24: F12 CTRL
	Description: Slot 24
	Types: ProductionSlot
