label-content-panel-title = Управление контентом
label-package-template-required = Требуется
button-package-template-download = Скачать
label-package-template-installed = Установлено
label-package-template-requires-source = Требуется диск
button-content-panel-check-source = Найти диск или установку
label-source-tooltip-description = Источники контента:
button-package-download-panel-retry = Повторить
label-content-prompt-panel-title = Установить контент
button-content-prompt-panel-advanced = Дополнительные параметры установки
button-content-prompt-panel-quick = Быстрая установка
label-downloading = Загрузка { $title }
label-fetching-mirror-list = Получение списка зеркал...
label-downloading-from = Загрузка с { $host } { $received } { $suffix }
label-downloading-from-progress = Загрузка с { $host } { $received } / { $total } { $suffix } ({ $progress }%)
label-unknown-host = неизвестный хост
label-download-failed = Ошибка загрузки
label-verifying-archive = Проверка архива...
label-archive-validation-failed = Ошибка проверки архива
label-extracting-archive = Извлечение...
label-extracting-archive-entry = Извлечение { $entry }
label-archive-extraction-failed = Ошибка извлечения архива
label-mirror-selection-failed = Онлайн-зеркало недоступно. Пожалуйста, установите с оригинального диска.
label-detecting-sources = Обнаружение дисководов
label-checking-sources = Проверка источников
label-searching-source-for = Поиск { $title }
label-content-package-installation = Выберите пакеты контента для установки:
label-game-sources = Источники файлов игры
label-digital-installs = Цифровые версии
label-game-content-not-found = Игровой контент не найден
label-alternative-content-sources = Пожалуйста, вставьте или установите один из следующих источников контента:
label-installing-content = Установка контента
label-copying-filename = Копирование { $filename }
label-copying-filename-progress = Копирование { $filename } ({ $progress }%)
label-installation-failed = Установка не удалась
label-check-install-log = Дополнительные сведения см. в файле install.log в каталоге logs.
label-extracting-filename = Извлечение { $filename }
label-extracting-filename-progress = Извлечение { $filename } ({ $progress }%)
button-manual-install = Ручная установка
