blank_issues_enabled: false
contact_links:
  - name: OpenRA Forum
    url: https://forum.openra.net/
    about: "Please ask questions about modding here."
  - name: OpenRA IRC Channel
    url: https://webchat.freenode.net/#openra
    about: "Join the #openra IRC channel on freenode for real time support."
