blank_issues_enabled: false
contact_links:
  - name: Frequently Asked Questions
    url: https://github.com/OpenRA/OpenRA/wiki/FAQ#frequently-asked-questions
    about: Explanations for common problems and questions.
  - name: OpenRA Forum
    url: https://forum.openra.net/
    about: Please ask questions about modding here.
  - name: OpenRA Discord server
    url: https://discord.openra.net/
    about: Join the community Discord server for community discussion and support.
  - name: OpenRA IRC Channel
    url: https://webchat.freenode.net/#openra
    about: Join our development IRC channel on freenode for discussion of development topics.
