#region Copyright & License Information
/*
 * Copyright (c) The OpenRA Developers and Contributors
 * This file is part of OpenRA, which is free software. It is made
 * available to you under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version. For more
 * information, see COPYING.
 */
#endregion

using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace OpenRA.Roslyn.SourceGenerators.Sync
{
	// https://andrewlock.net/exploring-dotnet-6-part-9-source-generator-updates-incremental-generators/
	[Generator]
	public class SyncHashCodeSourceGenerator : IIncrementalGenerator
	{
		public void Initialize(IncrementalGeneratorInitializationContext context)
		{
			var classSymbolProvider = context.SyntaxProvider
				.ForAttributeWithMetadataName(
					SyncHelpers.FullyQualifiedGenerateSyncCodeAttributeName,
					predicate: static (_, _) => true, // ForAttributeWithMetadataName() + the usage of the specific attribute mean we already know this is a class tagged for generation. We allow generation even if the class is not partial as a way of telling the user they're doing something wrong.
					transform: static (generatorContext, _) => GetClassDeclarationSymbol(generatorContext))
				.Where(static x => x != null);

			context.RegisterSourceOutput(classSymbolProvider,
				static (context, symbol) => ProcessClass(context, symbol));
		}

		static INamedTypeSymbol GetClassDeclarationSymbol(GeneratorAttributeSyntaxContext context)
		{
			if (context.TargetSymbol is INamedTypeSymbol typeSymbol
				&& !typeSymbol.ManuallyImplementsISync())
				return typeSymbol;

			return null;
		}

		static void ProcessClass(SourceProductionContext context, INamedTypeSymbol classSymbol)
		{
			if (classSymbol.ContainingNamespace == null)
				return;

			var syncedClassMembers = GetSyncHashElements(classSymbol);
			if (syncedClassMembers.Count == 0)
				return;

			var shouldCallBase = classSymbol.BaseType.HasOrInheritsGenerateSyncCodeAttribute();
			var (filename, content) = GenerateClass(classSymbol, syncedClassMembers, shouldCallBase);
			if (content != null)
				context.AddSource(filename, content);
		}

		static List<string> GetSyncHashElements(INamedTypeSymbol classSymbol)
		{
			// If not abstract, only care about your own members (and potentially call the base method later if needed).
			if (!classSymbol.IsAbstract)
				return classSymbol.GetMembers()
					.Where(static x => x.HasVerifySyncAttribute())
					.Select(static x => x.Name)
					.ToList();

			var symbol = classSymbol;
			var syncElements = new List<string>();

			while (symbol.IsAbstract && symbol.Name != "Object")
			{
				var members = symbol.GetMembers().Where(static x => x.HasVerifySyncAttribute());
				syncElements.AddRange(members.Select(static x => x.Name));
				symbol = symbol.BaseType;
			}

			return syncElements;
		}

		static (string FileName, string Content) GenerateClass(
			INamedTypeSymbol classSymbol, IEnumerable<string> syncMembers, bool shouldCallBase)
		{
			var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
			var classModifiers = SourceGeneratorHelpers.GetClassModifiers(classSymbol);
			var className = classSymbol.Name;
			var isSealed = classSymbol.IsSealed;
			var elements = syncMembers.Select(static x => $"Sync.Hash({x})");
			if (shouldCallBase)
				elements = Enumerable.Append(elements, "base.GetSyncHash()");

			return ($"{namespaceName}.{className}.g.cs",
				$@"// <auto-generated/>
#pragma warning disable CS1591 // Apparently disabling in .editorconfig doesn't work for generated code.
namespace {namespaceName}
{{
	{classModifiers} class {className} : {SyncHelpers.SyncInterfaceName}
	{{
		public {(shouldCallBase ? "override" : (isSealed ? "" : "virtual"))} int GetSyncHash()
		{{
			return {string.Join(" ^ ", elements)};
		}}
	}}
}}");
		}
	}
}
