#region Copyright & License Information
/*
 * Copyright (c) The OpenRA Developers and Contributors
 * This file is part of OpenRA, which is free software. It is made
 * available to you under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version. For more
 * information, see COPYING.
 */
#endregion

using System;
using System.Collections.Generic;

namespace OpenRA
{
	// List of scancodes representing physical key positions on the keyboard (based on SDL 2.0 SDL_Scancode values).
	// Unlike Keycode, these values are layout-independent and represent the physical location of keys on a US QWERTY keyboard.
	public enum Scancode
	{
		UNKNOWN = 0,

		// Letters (physical QWERTY positions)
		A = 4,
		B = 5,
		C = 6,
		D = 7,
		E = 8,
		F = 9,
		G = 10,
		H = 11,
		I = 12,
		J = 13,
		K = 14,
		L = 15,
		M = 16,
		N = 17,
		O = 18,
		P = 19,
		Q = 20,
		R = 21,
		S = 22,
		T = 23,
		U = 24,
		V = 25,
		W = 26,
		X = 27,
		Y = 28,
		Z = 29,

		// Number row (physical positions above letter row)
		NUMBER_1 = 30,
		NUMBER_2 = 31,
		NUMBER_3 = 32,
		NUMBER_4 = 33,
		NUMBER_5 = 34,
		NUMBER_6 = 35,
		NUMBER_7 = 36,
		NUMBER_8 = 37,
		NUMBER_9 = 38,
		NUMBER_0 = 39,

		// Control keys
		RETURN = 40,
		ESCAPE = 41,
		BACKSPACE = 42,
		TAB = 43,
		SPACE = 44,

		// Punctuation row (right of number row and letter rows)
		MINUS = 45,
		EQUALS = 46,
		LEFTBRACKET = 47,
		RIGHTBRACKET = 48,
		BACKSLASH = 49,
		NONUSHASH = 50,
		SEMICOLON = 51,
		APOSTROPHE = 52,
		GRAVE = 53,
		COMMA = 54,
		PERIOD = 55,
		SLASH = 56,

		// Function keys and special keys
		CAPSLOCK = 57,
		F1 = 58,
		F2 = 59,
		F3 = 60,
		F4 = 61,
		F5 = 62,
		F6 = 63,
		F7 = 64,
		F8 = 65,
		F9 = 66,
		F10 = 67,
		F11 = 68,
		F12 = 69,

		// Navigation cluster
		PRINTSCREEN = 70,
		SCROLLLOCK = 71,
		PAUSE = 72,
		INSERT = 73,
		HOME = 74,
		PAGEUP = 75,
		DELETE = 76,
		END = 77,
		PAGEDOWN = 78,

		// Arrow keys
		RIGHT = 79,
		LEFT = 80,
		DOWN = 81,
		UP = 82,

		// Numpad
		NUMLOCKCLEAR = 83,
		KP_DIVIDE = 84,
		KP_MULTIPLY = 85,
		KP_MINUS = 86,
		KP_PLUS = 87,
		KP_ENTER = 88,
		KP_1 = 89,
		KP_2 = 90,
		KP_3 = 91,
		KP_4 = 92,
		KP_5 = 93,
		KP_6 = 94,
		KP_7 = 95,
		KP_8 = 96,
		KP_9 = 97,
		KP_0 = 98,
		KP_PERIOD = 99,

		// Additional keys
		NONUSBACKSLASH = 100,
		APPLICATION = 101,
		POWER = 102,
		KP_EQUALS = 103,

		// Extended function keys
		F13 = 104,
		F14 = 105,
		F15 = 106,
		F16 = 107,
		F17 = 108,
		F18 = 109,
		F19 = 110,
		F20 = 111,
		F21 = 112,
		F22 = 113,
		F23 = 114,
		F24 = 115,

		// Miscellaneous keys
		EXECUTE = 116,
		HELP = 117,
		MENU = 118,
		SELECT = 119,
		STOP = 120,
		AGAIN = 121,
		UNDO = 122,
		CUT = 123,
		COPY = 124,
		PASTE = 125,
		FIND = 126,
		MUTE = 127,
		VOLUMEUP = 128,
		VOLUMEDOWN = 129,

		// Numpad additional keys
		KP_COMMA = 133,
		KP_EQUALSAS400 = 134,

		// International keys
		INTERNATIONAL1 = 135,
		INTERNATIONAL2 = 136,
		INTERNATIONAL3 = 137,
		INTERNATIONAL4 = 138,
		INTERNATIONAL5 = 139,
		INTERNATIONAL6 = 140,
		INTERNATIONAL7 = 141,
		INTERNATIONAL8 = 142,
		INTERNATIONAL9 = 143,

		// Language keys
		LANG1 = 144,
		LANG2 = 145,
		LANG3 = 146,
		LANG4 = 147,
		LANG5 = 148,
		LANG6 = 149,
		LANG7 = 150,
		LANG8 = 151,
		LANG9 = 152,

		// Editing keys
		ALTERASE = 153,
		SYSREQ = 154,
		CANCEL = 155,
		CLEAR = 156,
		PRIOR = 157,
		RETURN2 = 158,
		SEPARATOR = 159,
		OUT = 160,
		OPER = 161,
		CLEARAGAIN = 162,
		CRSEL = 163,
		EXSEL = 164,

		// Extended numpad keys
		KP_00 = 176,
		KP_000 = 177,
		THOUSANDSSEPARATOR = 178,
		DECIMALSEPARATOR = 179,
		CURRENCYUNIT = 180,
		CURRENCYSUBUNIT = 181,
		KP_LEFTPAREN = 182,
		KP_RIGHTPAREN = 183,
		KP_LEFTBRACE = 184,
		KP_RIGHTBRACE = 185,
		KP_TAB = 186,
		KP_BACKSPACE = 187,
		KP_A = 188,
		KP_B = 189,
		KP_C = 190,
		KP_D = 191,
		KP_E = 192,
		KP_F = 193,
		KP_XOR = 194,
		KP_POWER = 195,
		KP_PERCENT = 196,
		KP_LESS = 197,
		KP_GREATER = 198,
		KP_AMPERSAND = 199,
		KP_DBLAMPERSAND = 200,
		KP_VERTICALBAR = 201,
		KP_DBLVERTICALBAR = 202,
		KP_COLON = 203,
		KP_HASH = 204,
		KP_SPACE = 205,
		KP_AT = 206,
		KP_EXCLAM = 207,
		KP_MEMSTORE = 208,
		KP_MEMRECALL = 209,
		KP_MEMCLEAR = 210,
		KP_MEMADD = 211,
		KP_MEMSUBTRACT = 212,
		KP_MEMMULTIPLY = 213,
		KP_MEMDIVIDE = 214,
		KP_PLUSMINUS = 215,
		KP_CLEAR = 216,
		KP_CLEARENTRY = 217,
		KP_BINARY = 218,
		KP_OCTAL = 219,
		KP_DECIMAL = 220,
		KP_HEXADECIMAL = 221,

		// Modifier keys
		LCTRL = 224,
		LSHIFT = 225,
		LALT = 226,
		LGUI = 227,
		RCTRL = 228,
		RSHIFT = 229,
		RALT = 230,
		RGUI = 231,

		// Mode key
		MODE = 257,

		// Media keys
		AUDIONEXT = 258,
		AUDIOPREV = 259,
		AUDIOSTOP = 260,
		AUDIOPLAY = 261,
		AUDIOMUTE = 262,
		MEDIASELECT = 263,
		WWW = 264,
		MAIL = 265,
		CALCULATOR = 266,
		COMPUTER = 267,

		// Application control keys
		AC_SEARCH = 268,
		AC_HOME = 269,
		AC_BACK = 270,
		AC_FORWARD = 271,
		AC_STOP = 272,
		AC_REFRESH = 273,
		AC_BOOKMARKS = 274,

		// Display and keyboard illumination
		BRIGHTNESSDOWN = 275,
		BRIGHTNESSUP = 276,
		DISPLAYSWITCH = 277,
		KBDILLUMTOGGLE = 278,
		KBDILLUMDOWN = 279,
		KBDILLUMUP = 280,

		// System keys
		EJECT = 281,
		SLEEP = 282,

		// OpenRA custom: Mouse buttons treated as keyboard input
		MOUSE4 = 283,
		MOUSE5 = 284
	}

	public static class ScancodeExts
	{
		// Delegate to get layout-aware display names from the platform layer.
		// When set, this allows displaying key names according to the user's current keyboard layout.
		// For example, on AZERTY, the PERIOD scancode (physical position of "." on QWERTY) would display ":"
		public static Func<Scancode, string> GetLayoutAwareDisplayName;

		// Maps Scancode values to their corresponding Keycode fluent keys.
		// This allows reusing existing keycode translations for scancode display.
		static readonly IReadOnlyDictionary<Scancode, string> ScancodeToKeycodeFluentKey = new Dictionary<Scancode, string>()
		{
			{ Scancode.UNKNOWN, "keycode.unknown" },
			{ Scancode.A, "keycode.a" },
			{ Scancode.B, "keycode.b" },
			{ Scancode.C, "keycode.c" },
			{ Scancode.D, "keycode.d" },
			{ Scancode.E, "keycode.e" },
			{ Scancode.F, "keycode.f" },
			{ Scancode.G, "keycode.g" },
			{ Scancode.H, "keycode.h" },
			{ Scancode.I, "keycode.i" },
			{ Scancode.J, "keycode.j" },
			{ Scancode.K, "keycode.k" },
			{ Scancode.L, "keycode.l" },
			{ Scancode.M, "keycode.m" },
			{ Scancode.N, "keycode.n" },
			{ Scancode.O, "keycode.o" },
			{ Scancode.P, "keycode.p" },
			{ Scancode.Q, "keycode.q" },
			{ Scancode.R, "keycode.r" },
			{ Scancode.S, "keycode.s" },
			{ Scancode.T, "keycode.t" },
			{ Scancode.U, "keycode.u" },
			{ Scancode.V, "keycode.v" },
			{ Scancode.W, "keycode.w" },
			{ Scancode.X, "keycode.x" },
			{ Scancode.Y, "keycode.y" },
			{ Scancode.Z, "keycode.z" },
			{ Scancode.NUMBER_1, "keycode.number_1" },
			{ Scancode.NUMBER_2, "keycode.number_2" },
			{ Scancode.NUMBER_3, "keycode.number_3" },
			{ Scancode.NUMBER_4, "keycode.number_4" },
			{ Scancode.NUMBER_5, "keycode.number_5" },
			{ Scancode.NUMBER_6, "keycode.number_6" },
			{ Scancode.NUMBER_7, "keycode.number_7" },
			{ Scancode.NUMBER_8, "keycode.number_8" },
			{ Scancode.NUMBER_9, "keycode.number_9" },
			{ Scancode.NUMBER_0, "keycode.number_0" },
			{ Scancode.RETURN, "keycode.return" },
			{ Scancode.ESCAPE, "keycode.escape" },
			{ Scancode.BACKSPACE, "keycode.backspace" },
			{ Scancode.TAB, "keycode.tab" },
			{ Scancode.SPACE, "keycode.space" },
			{ Scancode.MINUS, "keycode.minus" },
			{ Scancode.EQUALS, "keycode.equals" },
			{ Scancode.LEFTBRACKET, "keycode.leftbracket" },
			{ Scancode.RIGHTBRACKET, "keycode.rightbracket" },
			{ Scancode.BACKSLASH, "keycode.backslash" },
			{ Scancode.SEMICOLON, "keycode.semicolon" },
			{ Scancode.APOSTROPHE, "keycode.quote" },
			{ Scancode.GRAVE, "keycode.backquote" },
			{ Scancode.COMMA, "keycode.comma" },
			{ Scancode.PERIOD, "keycode.period" },
			{ Scancode.SLASH, "keycode.slash" },
			{ Scancode.CAPSLOCK, "keycode.capslock" },
			{ Scancode.F1, "keycode.f1" },
			{ Scancode.F2, "keycode.f2" },
			{ Scancode.F3, "keycode.f3" },
			{ Scancode.F4, "keycode.f4" },
			{ Scancode.F5, "keycode.f5" },
			{ Scancode.F6, "keycode.f6" },
			{ Scancode.F7, "keycode.f7" },
			{ Scancode.F8, "keycode.f8" },
			{ Scancode.F9, "keycode.f9" },
			{ Scancode.F10, "keycode.f10" },
			{ Scancode.F11, "keycode.f11" },
			{ Scancode.F12, "keycode.f12" },
			{ Scancode.PRINTSCREEN, "keycode.printscreen" },
			{ Scancode.SCROLLLOCK, "keycode.scrolllock" },
			{ Scancode.PAUSE, "keycode.pause" },
			{ Scancode.INSERT, "keycode.insert" },
			{ Scancode.HOME, "keycode.home" },
			{ Scancode.PAGEUP, "keycode.pageup" },
			{ Scancode.DELETE, "keycode.delete" },
			{ Scancode.END, "keycode.end" },
			{ Scancode.PAGEDOWN, "keycode.pagedown" },
			{ Scancode.RIGHT, "keycode.right" },
			{ Scancode.LEFT, "keycode.left" },
			{ Scancode.DOWN, "keycode.down" },
			{ Scancode.UP, "keycode.up" },
			{ Scancode.NUMLOCKCLEAR, "keycode.numlockclear" },
			{ Scancode.KP_DIVIDE, "keycode.kp_divide" },
			{ Scancode.KP_MULTIPLY, "keycode.kp_multiply" },
			{ Scancode.KP_MINUS, "keycode.kp_minus" },
			{ Scancode.KP_PLUS, "keycode.kp_plus" },
			{ Scancode.KP_ENTER, "keycode.kp_enter" },
			{ Scancode.KP_1, "keycode.kp_1" },
			{ Scancode.KP_2, "keycode.kp_2" },
			{ Scancode.KP_3, "keycode.kp_3" },
			{ Scancode.KP_4, "keycode.kp_4" },
			{ Scancode.KP_5, "keycode.kp_5" },
			{ Scancode.KP_6, "keycode.kp_6" },
			{ Scancode.KP_7, "keycode.kp_7" },
			{ Scancode.KP_8, "keycode.kp_8" },
			{ Scancode.KP_9, "keycode.kp_9" },
			{ Scancode.KP_0, "keycode.kp_0" },
			{ Scancode.KP_PERIOD, "keycode.kp_period" },
			{ Scancode.APPLICATION, "keycode.application" },
			{ Scancode.POWER, "keycode.power" },
			{ Scancode.KP_EQUALS, "keycode.kp_equals" },
			{ Scancode.F13, "keycode.f13" },
			{ Scancode.F14, "keycode.f14" },
			{ Scancode.F15, "keycode.f15" },
			{ Scancode.F16, "keycode.f16" },
			{ Scancode.F17, "keycode.f17" },
			{ Scancode.F18, "keycode.f18" },
			{ Scancode.F19, "keycode.f19" },
			{ Scancode.F20, "keycode.f20" },
			{ Scancode.F21, "keycode.f21" },
			{ Scancode.F22, "keycode.f22" },
			{ Scancode.F23, "keycode.f23" },
			{ Scancode.F24, "keycode.f24" },
			{ Scancode.EXECUTE, "keycode.execute" },
			{ Scancode.HELP, "keycode.help" },
			{ Scancode.MENU, "keycode.menu" },
			{ Scancode.SELECT, "keycode.select" },
			{ Scancode.STOP, "keycode.stop" },
			{ Scancode.AGAIN, "keycode.again" },
			{ Scancode.UNDO, "keycode.undo" },
			{ Scancode.CUT, "keycode.cut" },
			{ Scancode.COPY, "keycode.copy" },
			{ Scancode.PASTE, "keycode.paste" },
			{ Scancode.FIND, "keycode.find" },
			{ Scancode.MUTE, "keycode.mute" },
			{ Scancode.VOLUMEUP, "keycode.volumeup" },
			{ Scancode.VOLUMEDOWN, "keycode.volumedown" },
			{ Scancode.KP_COMMA, "keycode.kp_comma" },
			{ Scancode.KP_EQUALSAS400, "keycode.kp_equalsas400" },
			{ Scancode.ALTERASE, "keycode.alterase" },
			{ Scancode.SYSREQ, "keycode.sysreq" },
			{ Scancode.CANCEL, "keycode.cancel" },
			{ Scancode.CLEAR, "keycode.clear" },
			{ Scancode.PRIOR, "keycode.prior" },
			{ Scancode.RETURN2, "keycode.return2" },
			{ Scancode.SEPARATOR, "keycode.separator" },
			{ Scancode.OUT, "keycode.out" },
			{ Scancode.OPER, "keycode.oper" },
			{ Scancode.CLEARAGAIN, "keycode.clearagain" },
			{ Scancode.CRSEL, "keycode.crsel" },
			{ Scancode.EXSEL, "keycode.exsel" },
			{ Scancode.KP_00, "keycode.kp_00" },
			{ Scancode.KP_000, "keycode.kp_000" },
			{ Scancode.THOUSANDSSEPARATOR, "keycode.thousandsseparator" },
			{ Scancode.DECIMALSEPARATOR, "keycode.decimalseparator" },
			{ Scancode.CURRENCYUNIT, "keycode.currencyunit" },
			{ Scancode.CURRENCYSUBUNIT, "keycode.currencysubunit" },
			{ Scancode.KP_LEFTPAREN, "keycode.kp_leftparen" },
			{ Scancode.KP_RIGHTPAREN, "keycode.kp_rightparen" },
			{ Scancode.KP_LEFTBRACE, "keycode.kp_leftbrace" },
			{ Scancode.KP_RIGHTBRACE, "keycode.kp_rightbrace" },
			{ Scancode.KP_TAB, "keycode.kp_tab" },
			{ Scancode.KP_BACKSPACE, "keycode.kp_backspace" },
			{ Scancode.KP_A, "keycode.kp_a" },
			{ Scancode.KP_B, "keycode.kp_b" },
			{ Scancode.KP_C, "keycode.kp_c" },
			{ Scancode.KP_D, "keycode.kp_d" },
			{ Scancode.KP_E, "keycode.kp_e" },
			{ Scancode.KP_F, "keycode.kp_f" },
			{ Scancode.KP_XOR, "keycode.kp_xor" },
			{ Scancode.KP_POWER, "keycode.kp_power" },
			{ Scancode.KP_PERCENT, "keycode.kp_percent" },
			{ Scancode.KP_LESS, "keycode.kp_less" },
			{ Scancode.KP_GREATER, "keycode.kp_greater" },
			{ Scancode.KP_AMPERSAND, "keycode.kp_ampersand" },
			{ Scancode.KP_DBLAMPERSAND, "keycode.kp_dblampersand" },
			{ Scancode.KP_VERTICALBAR, "keycode.kp_verticalbar" },
			{ Scancode.KP_DBLVERTICALBAR, "keycode.kp_dblverticalbar" },
			{ Scancode.KP_COLON, "keycode.kp_colon" },
			{ Scancode.KP_HASH, "keycode.kp_hash" },
			{ Scancode.KP_SPACE, "keycode.kp_space" },
			{ Scancode.KP_AT, "keycode.kp_at" },
			{ Scancode.KP_EXCLAM, "keycode.kp_exclam" },
			{ Scancode.KP_MEMSTORE, "keycode.kp_memstore" },
			{ Scancode.KP_MEMRECALL, "keycode.kp_memrecall" },
			{ Scancode.KP_MEMCLEAR, "keycode.kp_memclear" },
			{ Scancode.KP_MEMADD, "keycode.kp_memadd" },
			{ Scancode.KP_MEMSUBTRACT, "keycode.kp_memsubtract" },
			{ Scancode.KP_MEMMULTIPLY, "keycode.kp_memmultiply" },
			{ Scancode.KP_MEMDIVIDE, "keycode.kp_memdivide" },
			{ Scancode.KP_PLUSMINUS, "keycode.kp_plusminus" },
			{ Scancode.KP_CLEAR, "keycode.kp_clear" },
			{ Scancode.KP_CLEARENTRY, "keycode.kp_clearentry" },
			{ Scancode.KP_BINARY, "keycode.kp_binary" },
			{ Scancode.KP_OCTAL, "keycode.kp_octal" },
			{ Scancode.KP_DECIMAL, "keycode.kp_decimal" },
			{ Scancode.KP_HEXADECIMAL, "keycode.kp_hexadecimal" },
			{ Scancode.LCTRL, "keycode.lctrl" },
			{ Scancode.LSHIFT, "keycode.lshift" },
			{ Scancode.LALT, "keycode.lalt" },
			{ Scancode.LGUI, "keycode.lgui" },
			{ Scancode.RCTRL, "keycode.rctrl" },
			{ Scancode.RSHIFT, "keycode.rshift" },
			{ Scancode.RALT, "keycode.ralt" },
			{ Scancode.RGUI, "keycode.rgui" },
			{ Scancode.MODE, "keycode.mode" },
			{ Scancode.AUDIONEXT, "keycode.audionext" },
			{ Scancode.AUDIOPREV, "keycode.audioprev" },
			{ Scancode.AUDIOSTOP, "keycode.audiostop" },
			{ Scancode.AUDIOPLAY, "keycode.audioplay" },
			{ Scancode.AUDIOMUTE, "keycode.audiomute" },
			{ Scancode.MEDIASELECT, "keycode.mediaselect" },
			{ Scancode.WWW, "keycode.www" },
			{ Scancode.MAIL, "keycode.mail" },
			{ Scancode.CALCULATOR, "keycode.calculator" },
			{ Scancode.COMPUTER, "keycode.computer" },
			{ Scancode.AC_SEARCH, "keycode.ac_search" },
			{ Scancode.AC_HOME, "keycode.ac_home" },
			{ Scancode.AC_BACK, "keycode.ac_back" },
			{ Scancode.AC_FORWARD, "keycode.ac_forward" },
			{ Scancode.AC_STOP, "keycode.ac_stop" },
			{ Scancode.AC_REFRESH, "keycode.ac_refresh" },
			{ Scancode.AC_BOOKMARKS, "keycode.ac_bookmarks" },
			{ Scancode.BRIGHTNESSDOWN, "keycode.brightnessdown" },
			{ Scancode.BRIGHTNESSUP, "keycode.brightnessup" },
			{ Scancode.DISPLAYSWITCH, "keycode.displayswitch" },
			{ Scancode.KBDILLUMTOGGLE, "keycode.kbdillumtoggle" },
			{ Scancode.KBDILLUMDOWN, "keycode.kbdillumdown" },
			{ Scancode.KBDILLUMUP, "keycode.kbdillumup" },
			{ Scancode.EJECT, "keycode.eject" },
			{ Scancode.SLEEP, "keycode.sleep" },
			{ Scancode.MOUSE4, "keycode.mouse4" },
			{ Scancode.MOUSE5, "keycode.mouse5" },
		};

		public static string DisplayString(Scancode s)
		{
			// Try to get the layout-aware display name first (shows the actual key on user's keyboard)
			if (GetLayoutAwareDisplayName != null)
			{
				var layoutName = GetLayoutAwareDisplayName(s);
				if (!string.IsNullOrEmpty(layoutName))
					return layoutName;
			}

			// Fall back to Fluent translations
			if (!ScancodeToKeycodeFluentKey.TryGetValue(s, out var fluentKey))
				return s.ToString();

			return FluentProvider.GetMessage(fluentKey);
		}
	}
}
