label-assetbrowser-title = Обозреватель ресурсов
label-assetbrowser-source-selector-desc = Выберите источник ассетов
dropdownbutton-assetbrowser-source-selector = Папки
dropdownbutton-assetbrowser-asset-types-dropdown = Типы ресурсов
label-assetbrowser-filename-desc = Фильтр по имени
label-assetbrowser-sprite-scale = Масштаб:
label-assetbrowser-palette-desc = Палитра:
label-assetbrowser-sprite-bg-error = Ошибка при отображении файла. Подробности см. в assetbrowser.log.
button-color-chooser-random = Случайно
button-color-chooser-store = Сохранить / Открыть магазин (context-dependent)
button-color-chooser-mixer-tab = Микшер
button-color-chooser-palette-tab = Палитра
label-preset-header = Предустановленные цвета
label-custom-header = Пользовательские цвета
button-prompt-confirm = Подтвердить
button-prompt-other = Перезапуск
button-text-input-prompt-accept = ОК
label-connectionfailed-panel-password = Пароль:
button-connectionfailed-panel-abort = Прервать
label-connecting-panel-title = Подключение...
button-connecting-panel-abort = Прервать
label-connection-switchmod-panel-title = Переключить мод
label-connection-switchmod-panel-desc = На этом сервере запущен другой мод:
label-connection-switchmod-panel-desc2 = Переключить мод и подключиться к серверу?
button-connection-switchmod-panel-switch = Сменить
button-connection-switchmod-panel-abort = Прервать
label-openra = OpenRA
label-credits-title = Авторы
label-new-map-bg-title = Новая карта
label-new-map-bg-tileset = Окружение:
label-new-map-bg-width = Ширина:
label-new-map-bg-height = Высота:
button-new-map-bg-create = Создать
label-save-map-panel-heading = Сохранить карту
label-save-map-panel-title = Сохранить карту
label-save-map-panel-author = Автор:
label-save-map-panel-visibility = Видимость:
dropdownbutton-save-map-panel-visibility-dropdown = Видимость карты
label-save-map-panel-directory = Директория:
label-save-map-panel-filename = Имя файла:
button-save-map-panel = Сохранить
label-actor-edit-panel-id = ID
button-container-ok = ОК
label-tiles-bg-search = Поиск:
label-bg-filter = Фильтр:
label-actors-bg-search = Поиск:
label-actor-bg-owner = Владелец:
label-area-selection = Выделение области
label-area-info = Информация об области
label-selected-area-diagonal = Диагональ:
label-selected-area-resources = Ресурсы:
label-selection-filters = Фильтры
label-filter-terrain = Рельеф
label-filter-resources = Ресурсы
label-filter-actors = Объекты
label-tool-bg-category = Инструмент:
button-marker-tiles-clear-current = Очистить текущий
button-marker-tiles-clear-all = Очистить все
label-marker-layer-num-sides = Количество сторон
label-marker-alpha = Альфа тайла
label-marker-mirror-mode = Режим отражения
label-marker-axis-angle = Угол оси
button-map-generator-generate = Сгенерировать
button-map-generator-generate-random = Случайная генерация
label-tiling-path-type-start = Тип начала
label-tiling-path-type-inner = Внутренний тип
label-tiling-path-type-end = Тип конца
label-tiling-path-deviation = Лимит отклонения
checkbox-tiling-path-allow-end-deviation = Разрешить отклонение конечной точки
checkbox-tiling-path-closed-loops = Петли используют только внутренние типы
button-tiling-path-reverse = Обратный путь
button-tiling-path-reset = Сбросить путь
button-tiling-path-randomize = ПереRandomизировать / Перетасовать тайлы
button-tiling-path-paint = Нанести тайлы на карту
button-map-editor-tab-container-select-tooltip = Выделение
button-map-editor-tab-container-tiles-tooltip = Тайлы
button-map-editor-tab-container-overlays-tooltip = Наложения
button-map-editor-tab-container-actors-tooltip = Объекты
button-map-editor-tab-container-tools-tooltip = Инструменты
button-map-editor-tab-container-history-tooltip = История
button-delete-area =
    .label = Удалить
    .tooltip = Удалить все в выделенной области
button-delete-actor =
    .label = Удалить
    .tooltip = Удалить выбранный объект
button-editor-world-root-options =
    .label = Меню
    .tooltip = Меню
button-editor-world-root-copy-tooltip = Скопировать выделенную область
button-editor-world-root-paste-tooltip = Вставить сохраненную область
button-editor-world-root-undo-tooltip = Отменить последнее действие
button-editor-world-root-redo-tooltip = Повторить последнее действие
dropdownbutton-editor-world-root-overlay-button = Наложения
button-select-categories-buttons-all = Все
button-select-categories-buttons-none = Ничего
label-tool-marker-tiles = Тайлы-маркеры
label-tool-tiling-path = Дорожный тайлер
label-gamesave-browser-panel-load-title = Загрузить игру
label-gamesave-browser-panel-save-title = Сохранить игру
button-gamesave-browser-panel-delete-all = Удалить все
button-gamesave-browser-panel-delete = Удалить
button-gamesave-browser-panel-rename = Переименовать
button-gamesave-browser-panel-load = Загрузить
button-gamesave-browser-panel-save = Сохранить
label-gamesave-browser-panel-no-save-selected = Выберите сохранение для перезаписи или введите новое имя
label-load-game-browser-panel-title = Загрузить игру
label-load-game-browser-panel-choose-save = Выберите сохранённую игру
label-load-game-browser-panel-incompatible-title = Несовместимое сохранение
label-load-game-browser-panel-incompatible-a = Это сохранение несовместимо
label-load-game-browser-panel-incompatible-b = с этой версией OpenRA
label-load-game-browser-panel-human-player = Игрок
button-load-game-browser-panel-load = Загрузить
tooltip-savegame-date-created = Дата создания
tooltip-savegame-map = Карта
tooltip-savegame-duration = Длительность
tooltip-savegame-players = Количество игроков
button-chat-chrome-mode =
    .label = Команда
    .tooltip = Переключить режим чата
dropdownbutton-hpf-overlay-locomotor = Выберите тип движения
dropdownbutton-hpf-overlay-check = Выберите BlockedByActor
label-mission-objectives = Миссия:
label-script-error-panel-desc-a = В скрипте карты произошла критическая ошибка
label-script-error-panel-desc-b = Детали ошибки сохранены в файл lua.log в папке logs.
label-script-error-panel-desc-c = Пожалуйста, отправьте этот файл автору карты для исправления проблемы.
label-mission-objective = Миссия:
checkbox-stats-objective = Уничтожьте всех противников!
label-stats-player = Игрок
label-stats-faction = Фракция
label-stats-score = Счет
label-stats-actions = Действия
label-menu-buttons-title = Опции
label-kick-client-dialog-text-a = Вы также можете применить временный бан, предотвратив
label-kick-client-dialog-text-b = их присоединение до конца этой игры.
checkbox-kick-client-dialog-prevent-rejoining = Временный бан
button-kick-client-dialog = Выгнать
label-kick-spectators-dialog-title = Удалить зрителей
button-kick-spectators-dialog-ok = Ок
label-force-start-dialog-title = Начать игру?
label-force-start-dialog-text-a = Один или несколько игроков ещё не готовы.
label-force-start-dialog-text-b = Вы уверены, что хотите начать игру принудительно?
label-kick-warning-a = У одного или нескольких клиентов отсутствует выбранная
label-kick-warning-b = карта, и они будут исключены с сервера.
button-force-start-dialog-start = Начать
label-map-incompatible-status-a = Эта карта несовместима
label-map-incompatible-status-b = с данной версией OpenRA
label-map-validating-status = Проверка...
label-map-generating-status = Генерация...
button-map-download-available-install = Установить карту
button-map-preview-update = Обновить карту
button-map-update-download-available-install = Установить карту
label-map-preview-searching = Поиск в Центре ресурсов OpenRA...
label-map-unavailable-a = Карта не найдена в
label-map-unavailable-b = Центре ресурсов OpenRA
label-map-preview-error = Произошла ошибка при установке
label-map-update-available-a = Новая версия карты
label-map-update-available-b = обнаружена на вашем компьютере
label-music-controls-volume = Громкость:
label-music-title = Музыка
label-music-controls-length = Длина
checkbox-music-controls-shuffle = Перемешать
checkbox-music-controls-loop = Повтор
label-container-title = Трек
label-no-music-title = Музыка не установлена
label-no-music-desc-a = Музыку для игры можно установить
label-no-music-desc-b = в меню «Управление контентом».
button-replay-pause-tooltip = Пауза
button-replay-play-tooltip = Воспроизвести
button-replay-slow =
    .tooltip = Медленная скорость
    .label = 50%
button-replay-regular =
    .tooltip = Обычная скорость
    .label = 100%
button-replay-fast =
    .tooltip = Быстрая скорость
    .label = 200%
button-replay-maximum =
    .tooltip = Максимальная скорость
    .label = МАКС
label-basic-stats-player-header = Игрок
label-basic-stats-cash-header = Деньги
label-basic-stats-power-header = Энергия
label-basic-stats-kills-header = Убийства
label-basic-stats-deaths-header = Смерти
label-basic-stats-assets-destroyed-header = Уничтожено
label-basic-stats-assets-lost-header = Потеряно
label-basic-stats-experience-header = Счет
label-basic-stats-actions-min-header = ДПМ
label-economy-stats-player-header = Игрок
label-economy-stats-cash-header = Деньги
label-economy-stats-income-header = Доход
label-economy-stats-assets-header = Ресурсы
label-economy-stats-earned-header = Заработано
label-economy-stats-spent-header = Потрачено
label-production-stats-player-header = Игрок
label-production-stats-header = Производство
label-support-powers-player-header = Игрок
label-support-powers-header = Силы поддержки
label-army-player-header = Игрок
label-army-header = Армия
label-combat-stats-player-header = Игрок
label-combat-stats-assets-destroyed-header = Уничтожено
label-combat-stats-assets-lost-header = Потеряно
label-combat-stats-units-killed-header = Убито ед. техники
label-combat-stats-units-dead-header = Потеряно ед. техники
label-combat-stats-buildings-killed-header = Уничт. зданий
label-combat-stats-buildings-dead-header = Потеряно зданий
label-combat-stats-army-value-header = Ценность армии
label-combat-stats-vision-header = Обзор
label-mute-indicator = Звук отключен
button-top-buttons-options-tooltip = Опции
supportpowers-support-powers-palette =
    .ready = Готово
    .hold = На удержании
button-command-bar-attack-move =
    .tooltip = Атака в движении
    .tooltipdesc =
    Выбранные войска будут двигаться в указанную точку
    и атаковать любых врагов, встреченных по пути.

    Удерживайте <(Ctrl)> при указании цели, чтобы отдать приказ Штурмовать,
    чтобы атаковать любые войска или строения на пути.

    Щелкните левой кнопкой мыши по значку, затем правой кнопкой мыши по цели.
button-command-bar-guard =
    .tooltip = Охрана
    .tooltipdesc =
    Выбранные войска будут следовать за указанным объектом.

    Щелкните левой кнопкой мыши по значку, затем правой кнопкой мыши по цели.
button-command-bar-scatter =
    .tooltip = Рассредоточиться
    .tooltipdesc =
    Выбранные войска прекратят текущее действие
    и переместятся в ближайшее укрытие.

    Действует немедленно на выбранные войска.
button-command-bar-stop =
    .tooltip = Стоп
    .tooltipdesc =
    Выбранные войска прекратят текущее действие.
    Выбранные строения сбросят свою точку сбора.

    Действует немедленно на выбранные цели.
button-command-bar-queue-orders =
    .tooltip = Режим путевых точек
    .tooltipdesc =
    Используйте режим путевых точек, чтобы отдать несколько связанных приказов
    выбранным войскам. Войска будут выполнять приказы
    немедленно после их получения.

    Щелкните левой кнопкой мыши по значку, затем отдавайте приказы на карте.
    Удерживайте <(Shift)> для временной активации при командовании войсками.
button-stance-bar-attackanything =
    .tooltip = Атаковать все
    .tooltipdesc =
    Установить выбранным войскам поведение Атаковать все:
     - Войска будут атаковать вражеские войска и строения в поле зрения
     - Войска будут преследовать атакующих по всему полю боя
button-stance-bar-defend =
    .tooltip = Оборона
    .tooltipdesc =
    Установить выбранным войскам поведение Оборона:
     - Войска будут атаковать вражеские войска в поле зрения
     - Войска не будут двигаться или преследовать врагов
button-stance-bar-returnfire =
    .tooltip = Ответный огонь
    .tooltipdesc =
    Установить выбранным войскам поведение Ответный огонь:
     - Войска будут отвечать на атаки врагов
     - Войска не будут двигаться или преследовать врагов
button-stance-bar-holdfire =
    .tooltip = Не открывать огонь
    .tooltipdesc =
    Установить выбранным войскам поведение Не открывать огонь:
     - Войска не будут стрелять по врагам
     - Войска не будут двигаться или преследовать врагов
productionpalette-sidebar-production-palette =
    .ready = ГОТОВО
    .hold = НА УДЕРЖАНИИ
button-production-types-scroll-up-tooltip = Прокрутить вверх
button-production-types-scroll-down-tooltip = Прокрутить вниз
label-lobby-options-bin-title = Параметры карты
label-lobby-players-name = Имя
label-lobby-players-color = Цвет
label-lobby-players-faction = Фракция
label-lobby-players-team = Команда
label-lobby-players-handicap = Фора
label-lobby-players-spawn = Точка старта
label-lobby-players-ready = Готов
dropdownbutton-lobby-players-handicap-tooltip = Фора снижает боевую эффективность сил игрока
button-lobby-players-join = Играть в этом слоте
label-lobby-players-spectator = Зритель
checkbox-lobby-players-new-spectator-toggle = Разрешить зрителей?
button-lobby-players-spectate = Наблюдать
image-lobby-servers-bin-password-protected-tooltip = Требуется пароль
image-lobby-servers-bin-requires-authentication-tooltip = Требуется аккаунт на форуме OpenRA
dropdownbutton-lobby-servers-bin-filters = Фильтр игр
label-container-server = Сервер
label-container-players = Игроки
label-container-location = Расположение
label-container-status = Статус
label-notice-container-outdated-version = Вы используете устаревшую версию OpenRA. Загрузите последнюю версию с сайта www.openra.net
label-notice-container-unknown-version = Вы используете неизвестную версию OpenRA. Загрузите последнюю версию с сайта www.openra.net
label-notice-container-playtest-available = Предварительная версия OpenRA доступна для тестирования. Загрузите playtest с сайта www.openra.net
dropdownbutton-server-lobby-slots = Администрирование слотов
button-server-lobby-reset-options = По умолчанию
button-skirmish-tabs-players-tab = Игроки
button-skirmish-tabs-options-tab = Параметры
button-multiplayer-tabs-players-tab = Игроки
button-multiplayer-tabs-options-tab = Параметры
button-multiplayer-tabs-servers-tab = Серверы
button-server-lobby-changemap = Сменить карту
button-lobbychat-chat-mode =
    .label = Команда
    .tooltip = Переключить режим чата
button-server-lobby-start-game = Начать игру
button-server-lobby-disconnect = Покинуть игру
label-mainmenu-introduction-prompt-title = Установка боевого управления
label-mainmenu-introduction-prompt-desc-a = С возвращением, Командир! Настройте параметры боя с помощью опций ниже.
label-mainmenu-introduction-prompt-desc-b = Дополнительные опции можно настроить позже в меню Настроек.
label-mainmenu-system-info-prompt-title = Установка боевого управления
label-mainmenu-system-info-prompt-text-a = Мы хотели бы собрать некоторые системные данные, которые помогут нам оптимизировать OpenRA.
label-mainmenu-system-info-prompt-text-b = С вашего разрешения, следующие анонимные данные будут отправляться при каждом запуске игры:
checkbox-mainmenu-system-info-prompt-sysinfo = Отправить системную информацию
label-profile-section-header = Профиль
label-player-container = Имя игрока:
label-playercolor-container-color = Предпочтительный цвет:
label-display-section-header = Дисплей
label-battlefield-camera-dropdown = Камера поля боя:
label-ui-scale-dropdown = Масштаб интерфейса:
checkbox-cursordouble-container = Увеличить размер курсора
label-input-section-header = Управление
label-mouse-control-container = Схема управления:
label-mouse-control-desc-classic-selection = - Выбирайте юниты с помощью <Левой> кнопки мыши
label-mouse-control-desc-classic-commands = - Управляйте юнитами с помощью <Левой> кнопки мыши
label-mouse-control-desc-classic-orders = - Подтверждайте приказы с помощью <Левой> кнопки мыши
label-mouse-control-desc-classic-buildings = - Стройте строения с помощью <Левой> кнопки мыши
label-mouse-control-desc-classic-support = - Активируйте силы поддержки с помощью <Левой> кнопки мыши
label-mouse-control-desc-classic-zoom = - Масштабируйте поле боя с помощью <Колеса прокрутки>
label-mouse-control-desc-classic-zoom-modifier = - Масштабируйте поле боя с помощью <MODIFIER + Колесо прокрутки>
label-mouse-control-desc-classic-scroll-right = - Панорамируйте поле боя с помощью <Правой> кнопки мыши
label-mouse-control-desc-classic-scroll-middle = - Панорамируйте поле боя с помощью <Средней> кнопки мыши
label-mouse-control-desc-classic-edgescroll = или перемещением курсора к краю экрана
label-mouse-control-desc-otherrts-selection = - Выбирайте юниты с помощью <Левой> кнопки мыши
label-mouse-control-desc-otherrts-commands = - Управляйте юнитами с помощью <Правой> кнопки мыши
label-mouse-control-desc-otherrts-orders = - Подтверждайте приказы с помощью <Левой> кнопки мыши
label-mouse-control-desc-otherrts-buildings = - Стройте строения с помощью <Левой> кнопки мыши
label-mouse-control-desc-otherrts-support = - Активируйте силы поддержки с помощью <Левой> кнопки мыши
label-mouse-control-desc-otherrts-zoom = - Масштабируйте поле боя с помощью <Колеса прокрутки>
label-mouse-control-desc-otherrts-zoom-modifier = - Масштабируйте поле боя с помощью <MODIFIER + Колесо прокрутки>
label-mouse-control-desc-otherrts-scroll-right = - Панорамируйте поле боя с помощью <Правой> кнопки мыши
label-mouse-control-desc-otherrts-scroll-middle = - Панорамируйте поле боя с помощью <Средней> кнопки мыши
label-mouse-control-desc-otherrts-edgescroll = или перемещением курсора к краю экрана
label-mouse-control-desc-modern-selection = - Выбирайте юниты с помощью <Левой> кнопки мыши
label-mouse-control-desc-modern-commands = - Управляйте юнитами с помощью <Правой> кнопки мыши
label-mouse-control-desc-modern-orders = - Подтверждайте приказы с помощью <Правой> кнопки мыши
label-mouse-control-desc-modern-buildings = - Стройте строения с помощью <Левой> кнопки мыши
label-mouse-control-desc-modern-support = - Активируйте силы поддержки с помощью <Левой> кнопки мыши
label-mouse-control-desc-modern-zoom = - Масштабируйте поле боя с помощью <Колеса прокрутки>
label-mouse-control-desc-modern-zoom-modifier = - Масштабируйте поле боя с помощью <MODIFIER + Колесо прокрутки>
label-mouse-control-desc-modern-scroll-right = - Панорамируйте поле боя с помощью <Правой> кнопки мыши
label-mouse-control-desc-modern-scroll-middle = - Панорамируйте поле боя с помощью <Средней> кнопки мыши
label-mouse-control-desc-modern-edgescroll = или путем перемещения курсора к краю экрана
checkbox-edgescroll-container = Прокрутка у края экрана
label-main-menu-title = Главное меню
label-singleplayer-title = Одиночная игра
button-extras-title = Дополнительно
button-main-menu-content = Управление контентом
button-singleplayer-menu-skirmish = Схватка
button-singleplayer-menu-load = Загрузить
button-extras-menu-replays = Повторы
label-map-editor-title = Редактор карт
button-extras-menu-assetbrowser = Обозреватель ресурсов
button-map-editor-new-map = Новая карта
button-map-editor-load-map = Загрузить карту
dropdownbutton-news-bg-button = Новости поля боя
label-update-notice-a = Вы используете устаревшую версию OpenRA.
label-update-notice-b = Загрузите последнюю версию с сайта www.openra.net
label-missions-title = Миссии
label-multiplayer-title = Многопользовательская игра
button-settings-title = Настройки
label-mapchooser-panel-title = Выбор карты
label-filter-order-controls-desc = Фильтр:
label-filter-order-controls-desc-joiner = в
label-filter-order-controls-orderby = Сортировать по:
button-mapchooser-panel-randommap = Случайная карта
button-mapchooser-panel-delete-map = Удалить карту
button-mapchooser-panel-delete-all-maps = Удалить все карты
button-mapchooser-panel-ok = Ок
label-mapchooser-random-map-title = Случайная карта
label-mapchooser-random-map-generating = Генерация...
label-mapchooser-random-map-error = Ошибка генерации
button-mapchooser-random-map-generate = Сгенерировать
label-mapchooser-random-map-tileset = Окружение:
label-mapchooser-random-map-size = Размер:
label-mapchooser-random-map-error-desc = Не удалось сгенерировать карту. Попробуйте снова.
button-missionbrowser-panel-start-briefing-video = Воспроизвести брифинг
button-missionbrowser-panel-stop-briefing-video = Остановить брифинг
button-missionbrowser-panel-start-info-video = Смотреть информационное видео
button-missionbrowser-panel-stop-info-video = Остановить видео
button-missionbrowser-panel-play = Играть
button-missionbrowser-panel-mission-info = Информация о миссии
button-missionbrowser-panel-mission-options = Опции миссии
dropdown-missionbrowser-difficulty =
    .label = Сложность
    .description = Сложность миссии
dropdown-missionbrowser-gamespeed = Скорость игры
label-missionbrowser-normal-difficulty = Обычная
image-multiplayer-panel-password-protected-tooltip = Требуется пароль
image-multiplayer-panel-requires-authentication-tooltip = Требуется учетная запись на форуме OpenRA
button-selected-server-join = Присоединиться
dropdownbutton-multiplayer-panel-filters = Фильтр игр
button-multiplayer-panel-directconnect = Прямой IP
button-multiplayer-panel-create = Создать
checkbox-multiplayer-filter-panel-waiting-for-players = Ожидание
checkbox-multiplayer-filter-panel-empty = Пусто
checkbox-multiplayer-filter-panel-password-protected = Защищено
checkbox-multiplayer-filter-panel-already-started = Началось
checkbox-multiplayer-filter-panel-incompatible-version = Несовместимая версия
label-multiplayer-createserver-panel-title = Создать сервер
label-multiplayer-createserver-panel-server-name = Имя сервера:
label-multiplayer-createserver-panel-password = Пароль:
label-multiplayer-createserver-panel-after-password = (необязательно)
label-multiplayer-createserver-panel-listen-port = Порт:
checkbox-multiplayer-createserver-panel-advertise = Рекламировать в сети
label-notices-lan-advertising = - Игра будет видна только в локальной сети.
label-notices-lan-firewall = - Вы должны вручную настроить брандмауэр для разрешения подключений.
label-notices-lan-portforward-a = - Игроки из интернета смогут подключиться по прямому IP, если вы
label-notices-lan-portforward-b = вручную настроите переадресацию портов на вашем роутере.
label-notices-no-upnp-advertising = - Игра будет видна в локальной сети и интернете.
label-notices-no-upnp-firewall = - Вы должны вручную настроить брандмауэр для разрешения подключений.
label-notices-no-upnp-portforward-a = Вам необходимо вручную настроить ваш роутер для разрешения и переадресации
label-notices-no-upnp-portforward-b = подключения к вашему локальному IP и порту.
label-notices-no-upnp-settings-a = - Вы можете включить UPnP/NAT-PMP (если поддерживается вашим роутером)
label-notices-no-upnp-settings-b = во вкладке 'Дополнительно' в меню настроек.
label-notices-upnp-advertising = - Игра будет видна в локальной сети и интернете.
label-notices-upnp-firewall = Вам необходимо вручную настроить межсетевой экран для разрешения соединений.
label-notices-upnp-portforward-a = Игра автоматически настроит переадресацию портов.
label-notices-upnp-settings-a = Вы можете отключить UPnP/NAT-PMP в меню настроек.
button-multiplayer-createserver-panel-change-map = Сменить карту
button-multiplayer-createserver-panel-create = Создать
label-directconnect-panel-title = Подключиться к серверу
label-directconnect-panel-address = Адрес сервера:
label-directconnect-panel-port = :
button-directconnect-panel-join = Присоединиться
button-profile-header-logout = Выйти
label-generate-keys-desc-a = Подключиться к учетной записи форума для идентификации
label-generate-keys-desc-b = вас другим игрокам, подключаться к приватным
label-generate-keys-desc-c = серверам и отображать значки.
button-generate-keys-key = Войти в учетную запись форума OpenRA
label-generating-keys-desc-a = Генерация пары ключей аутентификации.
label-generating-keys-desc-b = Это займет несколько секунд...
label-register-fingerprint-desc-a = Ключ аутентификации скопирован в буфер обмена.
label-register-fingerprint-desc-b = Буфер обмена. Добавьте это в Панель управления пользователя
label-register-fingerprint-desc-c = на форуме OpenRA, затем нажмите «Продолжить»
label-checking-fingerprint-desc-a = Запрос сведений об учетной записи
label-checking-fingerprint-desc-b = форум OpenRA...
label-fingerprint-not-found-desc-a = Ключ аутентификации не подключен
label-fingerprint-not-found-desc-b = к учётной записи на форуме OpenRA.
label-connection-error-desc-a = Не удалось подключиться к форуму OpenRA.
label-connection-error-desc-b = Проверьте интернет
label-replaybrowser-panel-title = Повторы
label-filters-title = Фильтры
label-filters-flt-name-desc = Название:
label-filters-flt-gametype-desc = Тип игры:
dropdownbutton-filters-any = Любой
label-filters-flt-date-desc = Дата:
label-filters-flt-duration-desc = Длительность:
label-filters-flt-mapname-desc = Карта:
label-filters-flt-player-desc = Игрок:
dropdownbutton-filters-flt-player = Любой
label-filters-flt-outcome-desc = Исход:
label-filters-flt-faction-desc = Фракция:
button-filters-flt-reset = Сбросить
label-management-manage-title = Управление
button-management-mng-rensel = Переименовать
button-management-mng-delsel = Удалить
button-management-mng-delall = Удалить все
checkbox-load-game-filters = Показать фильтры
label-replay-list-container-replaybrowser-title = Браузер повторов
button-replaybrowser-panel-watch = Смотреть
label-network-section-header = Дополнительные
checkbox-nat-discovery-container = Включить обнаружение UPnP/NAT-PMP
checkbox-fetch-news-container = Получать новости сообщества
checkbox-perfgraph-container = График производительности
checkbox-check-version-container = Проверить наличие обновлений
checkbox-perftext-container = Показатели производительности
checkbox-sendsysinfo-container = Отправить системную информацию
label-sendsysinfo-checkbox-container-desc = Ваши версии ОС, OpenGL и среды .NET, а также языковые настройки будут отправляться с анонимным ID для помощи в приоритизации разработки.
label-debug-section-header = Отладка
label-debug-hidden-container-a = Дополнительные параметры для разработчиков можно включить через
label-debug-hidden-container-b = параметр Debug.DisplayDeveloperSettings или флаг запуска
checkbox-botdebug-container = Отладка ботов
checkbox-checkbotsync-container = Проверка синхронизации кода модуля бота
checkbox-luadebug-container = Отладочные сообщения карты
checkbox-checkunsynced-container = Проверка синхронизации несинхронизированного кода
checkbox-replay-commands-container = Включить отладочные команды в повторах
checkbox-perflogging-container = Включить логирование производительности тиков
label-audio-section-header = Аудио
label-no-audio-device-container = Для управления аудио требуется активное звуковое устройство
checkbox-cash-ticks-container = Звук кредитов
checkbox-mute-sound-container = Отключить звук
label-sound-volume-container = Громкость звука
checkbox-mute-background-music-container =
    .label = Отключить музыку меню
    .tooltip = Отключить фоновую музыку при отсутствии активного трека
label-music-title-volume-container = Громкость музыки
label-audio-device-container = Аудиоустройство
label-video-volume-container = Громкость видео
label-restart-required-container-audio-desc = Изменения устройства вступят в силу после перезапуска игры
label-gameplay-section-header = Геймплей
label-auto-save-interval = Интервал автосохранения
label-auto-save-max-file-number = Лимит автосохранений:
checkbox-hide-replay-chat-container = Скрыть чат в повторах
label-target-lines-dropdown-container = Линии прицеливания
label-status-bar-dropdown-container-bars = Полосы состояния
checkbox-player-stance-colors-container =
    .label = Цвета отношений игроков
    .tooltip = Изменять цвет игрока в зависимости от отношений (свои, враги, союзники, нейтральные)

checkbox-ui-feedback-container =
    .label = Показывать уведомления интерфейса
    .tooltip = Показывать временные текстовые уведомления для событий интерфейса

checkbox-transients-container =
    .label = Показывать игровые уведомления
    .tooltip = Показывать временные текстовые уведомления для игровых событий
checkbox-pause-shellmap-container = Фон меню паузы
label-video-section-header = Видео
label-video-mode-dropdown-container = Режим видео
dropdownbutton-video-mode-dropdown-container = Оконный режим
label-window-resolution-container-size = Размер окна
label-window-resolution-container-x = x
label-resolution-preset = Пресеты:
dropdownbutton-resolution-select-preset = Выберите пресет
label-display-selection-container = Монитор
dropdownbutton-display-selection-container-dropdown = Выбор монитора
checkbox-vsync-container = Вертикальная синхронизация (VSync)
checkbox-frame-limit-gamespeed-container = Ограничить частоту кадров частотой игровых тиков
label-gl-profile-dropdown-container = Профиль OpenGL
label-restart-required-container-video-desc = Изменения дисплея и OpenGL требуют перезапуска
label-language-section-header = Язык
label-language-dropdown-container = Язык интерфейса:
label-restart-required-container-language-desc = Смена языка требует перезапуска
hotkey-group-game-commands = Игровые команды
hotkey-group-viewport-commands = Управление камерой
hotkey-group-observer-replay-commands = Команды зрителя/повтора
hotkey-group-unit-commands = Команды войск
hotkey-group-unit-stance-commands = Команды режима войск
hotkey-group-production-commands = Производственные команды
hotkey-group-support-power-commands = Команды поддержки
hotkey-group-music-commands = Управление музыкой
hotkey-group-chat-commands = Команды чата
hotkey-group-control-groups = Группы управления
hotkey-group-editor-commands = Команды редактора
label-hotkeys-panel-filter-input = Фильтр:
label-hotkeys-panel-context-dropdown = Контекст:
label-hotkey-empty-list-message = Горячие клавиши не найдены.
label-notices-readonly-notice = Этот хоткей нельзя изменить
button-hotkey-remap-dialog-override = Заменить
button-hotkey-remap-dialog-clear =
    .label = Очистить
    .tooltip = Убрать привязку горячей клавиши

button-hotkey-remap-dialog-reset =
    .label = Сбросить
    .tooltip = Сбросить к значению по умолчанию
label-zoom-modifier-container = Модификатор масштаба
checkbox-alternate-scroll-container = Альтернативная прокрутка мышью
checkbox-lockmouse-container = Привязать мышь к окну
label-mouse-scroll-type-container = Режим прокрутки:
label-scrollspeed-slider-container-scroll-speed = Скорость прокрутки
label-zoomspeed-slider-container-zoom-speed = Скорость масштабирования
label-ui-scrollspeed-slider-container-scroll-speed = Скорость прокрутки интерфейса
button-settings-panel-reset = Сбросить все
button-panel-gameplay = Геймплей
button-panel-input = Управление
button-panel-language = Язык
button-panel-display = Дисплей
button-panel-audio = Аудио
button-panel-hotkeys = Горячие клавиши
button-panel-advanced = Дополнительные
label-latency-tooltip-prefix = Задержка:
label-anonymous-player-tooltip-name = Аноним
label-bot-player-tooltip-name = Бот
label-bot-managed-by-tooltip = Управляется ботом: { $name }
label-game-admin = Админ игры
label-gamesave-loading-screen-title = Загрузка сохраненной игры
label-gamesave-loading-screen-desc = Нажмите Escape для отмены загрузки и возврата в главное меню
