button-cancel = Отмена
button-retry = Повторить
button-back = Назад
button-continue = Продолжить
button-quit = Выйти
notification-custom-rules = Эта карта содержит пользовательские правила. Игровой опыт может измениться.
notification-two-humans-required = На этом сервере для начала матча требуется как минимум два игрока-человека.
notification-unknown-server-command = Неизвестная команда сервера: { $command }.
notification-admin-start-game = Только хост может начать игру.
notification-no-start-until-required-slots-full = Невозможно начать игру, пока не будут заняты все необходимые слоты.
notification-no-start-without-players = Игра не может начаться без игроков.
notification-insufficient-enabled-spawn-points = Невозможно начать игру, пока не будет включено больше точек появления.
notification-malformed-command = Неправильный формат команды { $command }.
notification-state-unchanged-ready = Невозможно изменить состояние, если указана готовность.
notification-invalid-faction-selected = Выбрана недействительная фракция: { $faction }.
notification-state-unchanged-game-started = Состояние не может быть изменено после начала игры ({ $command }).
notification-requires-host = выполнить это / добиться этого
notification-invalid-bot-slot = Невозможно добавить ботов в слот с другим клиентом.
notification-invalid-bot-type = Неверный тип бота.
notification-admin-change-map = Только хост может изменить карту.
notification-player-disconnected = { $player } отключился.
notification-team-player-disconnected = вышел из игры
notification-observer-disconnected = { $player } (Зритель) отключился.
notification-unknown-map = Карта не найдена на сервере.
notification-searching-map = Центр ресурсов
notification-admin-change-configuration = Только хост может изменить конфигурацию.
notification-changed-map = { $player } изменил карту на { $map }.
notification-you-were-kicked = Вас исключили с сервера.
notification-admin-kicked = { $admin } исключил { $player } с сервера.
notification-kicked = { $player } был исключен с сервера.
notification-temp-ban = { $admin } временно забанил { $player } на сервере.
notification-admin-transfer-admin = Только администраторы могут передать права администратора другому игроку.
notification-admin-move-spectators = перевести игроков в статус зрителей
notification-empty-slot = На этой позиции
notification-move-spectators = { $admin } переместил { $player } в зрители.
notification-nick-changed = { $player } теперь известен как { $name }.
notification-player-dropped = Игрок был исключен по истечении времени ожидания.
notification-connection-problems = У { $player } проблемы с подключением.
notification-timeout-dropped = { $player } был исключен по истечении времени ожидания.
notification-timeout-dropped-in = { $timeout ->
        [one] { $player } будет исключен через { $timeout } секунду.
        [few] { $player } будет исключен через { $timeout } секунды.
        [many] { $player } будет исключен через { $timeout } секунд.
       *[other] { $player } будет исключен через { $timeout } секунд.
    }
notification-error-game-started = Игра уже началась.
notification-requires-password = Сервер требует пароль.
notification-incorrect-password = Неверный пароль.
notification-incompatible-mod = Сервер использует несовместимый мод.
notification-incompatible-version = Сервер использует несовместимую версию.
notification-incompatible-protocol = Сервер использует несовместимый протокол.
notification-you-were-banned = Вы были забанены на сервере.
notification-you-were-temp-banned = Вы были временно забанены на сервере.
notification-game-full = Игра заполнена
notification-new-admin = { $player } теперь администратор.
notification-invalid-configuration-command = Неверная команда конфигурации.
notification-admin-option = настроить эту опцию
notification-error-number-teams = Не удалось определить количество команд: { $raw }.
notification-admin-kick = Только хост может исключать игроков.
notification-kick-self = Хост не может исключить самого себя.
notification-kick-none = На этой позиции
notification-no-kick-game-started = проигравшие игроки
notification-admin-clear-spawn = Только администраторы могут очищать точки возрождения.
notification-spawn-occupied = Вы не можете занять ту же точку возрождения, что и другой игрок.
notification-spawn-locked = Точка возрождения привязана к слоту другого игрока.
notification-admin-lobby-info = изменять настройки лобби
notification-invalid-lobby-info = Отправлена неверная информация лобби.
notification-player-color-terrain = Цвет был изменен, чтобы меньше сливаться с ландшафтом.
notification-player-color-player = Цвет был изменен, чтобы меньше сливаться с другим игроком.
notification-invalid-player-color = Невозможно определить допустимый цвет игрока. Был выбран случайный цвет.
notification-invalid-error-code = Не удалось обработать сообщение об ошибке.
notification-master-server-connected = Связь с мастер-сервером установлена.
notification-master-server-error = Ошибка связи с мастер-сервером.
notification-game-offline = рекламировалась в интернете
notification-no-port-forward = Порт сервера недоступен из интернета.
notification-blacklisted-server-name = Имя сервера содержит запрещенное слово.
notification-requires-authentication = Сервер требует наличия учетной записи на форуме OpenRA.
notification-no-permission-to-join = У вас нет разрешения на подключение к этому серверу.
notification-slot-closed = хост закрыл ваш слот
notification-joined = { $player } присоединился к игре.
notification-lobby-disconnected = { $player } покинул игру.
notification-game-has-started = Игра началась.
notification-game-paused = Игра была поставлена на паузу игроком { $player }.
notification-game-unpaused = Игра была снята с паузы игроком { $player }.
notification-game-started = Игра началась.
notification-chat-temp-disabled = { $remaining ->
        [one] Чат отключен. Пожалуйста, попробуйте снова через { $remaining } секунду.
        [few] Чат отключен. Пожалуйста, попробуйте снова через { $remaining } секунды.
        [many] Чат отключен. Пожалуйста, попробуйте снова через { $remaining } секунд.
       *[other] Чат отключен. Пожалуйста, попробуйте снова через { $remaining } секунд.
    }
notification-unable-to-start-a-vote = Невозможно начать голосование.
notification-insufficient-votes-to-kick = Недостаточно голосов для исключения игрока { $kickee }.
notification-kick-already-voted = Вы уже проголосовали.
notification-vote-kick-started = Игрок { $kicker } начал голосование за исключение игрока { $kickee }.
notification-vote-kick-in-progress = { $percentage }% игроков проголосовали за исключение игрока { $kickee }.
notification-vote-kick-ended = Голосование за исключение игрока { $kickee } не прошло.
label-duplicate-actor-id = Дублирующийся ID объекта
label-actor-id = Введите ID актора
label-actor-owner = Владелец
label-actor-type = Тип: { $actorType }
options-common-selector =
    .search-results = Результаты поиска
    .all = Все
    .multiple = Несколько
    .none = Нет
label-unpacked-map = распакована
dialog-save-map-failed =
    .title = Не удалось сохранить карту
    .prompt = Подробности см. в debug.log.
    .confirm = ОК
dialog-overwrite-map-failed =
    .title = Предупреждение
    .prompt = Сохранение перезапишет
    уже существующую карту.
    .confirm = Сохранить
dialog-overwrite-map-outside-edit =
    .title = Предупреждение
    .prompt = Карта была изменена вне редактора.
    Сохранение может перезаписать эти изменения.
    .confirm = Сохранить
notification-save-current-map = Текущая карта сохранена.
menu-game-info =
    .objectives = Цели
    .briefing = Брифинг
    .options = Настройки
    .debug = Читы
    .chat = Чат
label-mission-in-progress = В процессе
label-mission-accomplished = Достигнут / Завершен / Успешно
label-mission-failed = Не удалось
label-mute-player = Отключить звук для этого игрока
label-unmute-player = Включить звук для этого игрока
button-kick-player = Исключить этого игрока
button-vote-kick-player = Вынести игрока
dialog-kick =
    .title = Исключить { $player }?
    .prompt = Этот игрок не сможет снова присоединиться к игре.
    .confirm = Исключить
dialog-vote-kick =
    .title = Голосовать за исключение { $player }?
    .prompt = Этот игрок не сможет снова присоединиться к игре.
    .prompt-break-bots =
    { $bots ->
        [one] Исключение администратора игры также исключит 1 бота.
        [few] Исключение администратора игры также исключит { $bots } бота.
        [many] Исключение администратора игры также исключит { $bots } ботов.
       *[other] Исключение администратора игры также исключит { $bots } ботов.
    }
    .vote-start = Начать голосование
    .vote-for = За
    .vote-against = Против
    .vote-cancel = Воздержаться
notification-vote-kick-disabled = Кик-голосование
label-paused = Пауза
label-max-speed = Макс. скорость
label-replay-speed = { $percentage }% Скорость
label-replay-complete = { $percentage }% завершено
label-chat-disabled = Чат отключен
label-chat-availability = Через { $seconds } сек.
label-bot-player = Игрок ИИ
notification-lobby-option = { $name }: { $value }.
notification-lobby-option-changed = { $name } изменено на { $value }.
notification-map-bots-disabled = Боты были отключены на этой карте.
menu-ingame =
    .leave = Покинуть игру
    .abort = Прервать миссию
    .restart = Перезапустить
    .surrender = Сдаться
    .load-game = Загрузить игру
    .save-game = Сохранить игру
    .music = Музыка
    .settings = Настройки
    .return-to-map = Вернуться к карте
    .resume = Продолжить
    .save-map = Сохранить карту
    .exit-map = Выйти из редактора
dialog-leave-mission =
    .title = Покинуть миссию
    .prompt = Покинуть эту игру и вернуться в меню?
    .confirm = Покинуть
    .cancel = Остаться
dialog-restart-mission =
    .title = Перезапуск
    .prompt = Вы уверены, что хотите перезапустить игру?
    .confirm = Перезапустить
    .cancel = Остаться
dialog-surrender =
    .title = Сдаться
    .prompt = Вы уверены, что хотите сдаться?
    .confirm = Сдаться
    .cancel = Остаться
dialog-error-max-player =
    .title = Ошибка: Превышено максимальное число игроков
    .prompt = Указано слишком много игроков ({ $players }/{ $max }).
    .confirm = Назад
dialog-exit-map-editor =
    .title = Выйти из редактора карт
    .prompt-unsaved = Выйти и потерять все несохраненные изменения?
    .prompt-deleted = Возможно, карта была удалена вне редактора
    .confirm-anyway = Все равно выйти
    .confirm = Выйти
dialog-play-map-warning =
    .title = Внимание
    .prompt = Возможно, карта была удалена или содержит
    ошибки, препятствующие ее загрузке.
    .cancel = ОК
dialog-exit-to-map-editor =
    .title = Покинуть миссию
    .prompt = Покинуть эту игру и вернуться в редактор?
    .confirm = Вернуться в редактор
    .cancel = Остаться
label-power-usage = Энергопотребление: { $usage }/{ $capacity }
label-infinite-power = Бесконечно
label-silo-usage = Заполненность хранилищ: { $usage }/{ $capacity }
options-shroud-selector =
    .all-players = Все игроки
    .disable-shroud = Отключить завесу
    .other = Другое
options-observer-stats =
    .none = Информация: Нет
    .basic = Базовая
    .economy = Экономика
    .production = Производство
    .support-powers = Силы поддержки
    .combat = Бой
    .army = Армия
    .earnings-graph = Доход (график)
    .army-graph = Армия (график)
label-unrevealed-terrain = Неизведанная территория
dialog-kick-client =
    .prompt = Выгнать { $player }?
dialog-kick-spectators =
    .prompt =
    { $count ->
        [one] Вы уверены, что хотите выгнать одного зрителя?
       *[other] Вы уверены, что хотите выгнать { $count } зрителей?
    }
options-slot-admin =
    .add-bots = Добавить
    .remove-bots = Удалить
    .configure-bots = Настроить ботов
    .teams-count = Команд: { $count }
    .humans-vs-bots = Люди против Ботов
    .free-for-all = Каждый сам за себя
    .configure-teams = Настроить команды
button-general-chat = Все
button-team-chat = Команда
label-not-available = Недоступно
options-lobby-slot =
    .slot = Слот
    .open = Открыт
    .closed = Закрыт
    .bots = Боты
    .bots-disabled = Боты отключены
label-connecting = Подключение...
label-downloading-map = Загрузка: { $size } КБ
label-downloading-map-progress = Загрузка: { $size } КБ ({ $progress }%)
button-retry-install = Повторить установку
button-retry-search = Повторить поиск
label-created-by = Создано { $author }
label-disabled-spawn = зона возрождения
label-available-spawn = зона появления
options-camera =
    .close = Близко
    .medium = Средне
    .far = Далеко
    .furthest = Дальше всего
options-display-mode =
    .windowed = В окне
    .legacy-fullscreen = На весь экран (Устаревш.)
    .fullscreen = На весь экран
label-video-display-index = Экран
options-status-bars =
    .standard = Стандартные
    .show-on-damage = При получении урона
    .always-show = Всегда показывать
options-target-lines =
    .automatic = Автоматически
    .manual = Вручную
    .disabled = Отключены
checkbox-frame-limiter = Включить ограничение кадров ({ $fps } FPS)
label-original-notice = По умолчанию: "{ $key }"
label-duplicate-notice = Это уже используется для "{ $key }" в контексте { $context }
hotkey-context-any = Любой
auto-save-interval =
    .disabled = Отключено
    .options =
        { $seconds ->
            [one] 1 секунда
           *[other] { $seconds } секунд
        }
    .minute-options =
        { $minutes ->
            [one] 1 минута
           *[other] { $minutes } минут
        }
auto-save-max-file-number = { $saves } сохранений
options-mouse-scroll-type =
    .disabled = Отключена
    .standard = Стандартная
    .inverted = Инвертированная
    .joystick = Джойстик
options-control-scheme =
    .classic = Классическая
    .modern = Современная
    .otherrts = Другие RTS
dialog-settings-save =
    .title = Требуется перезапуск
    .prompt = Некоторые изменения не вступят в силу
    до перезапуска игры.
    .cancel = Продолжить
dialog-settings-restart =
    .title = Перезапустить сейчас?
    .prompt = Некоторые изменения не вступят в силу
    до перезапуска игры. Перезапустить сейчас?
    .confirm = Перезапустить сейчас
    .cancel = Перезапустить позже
dialog-settings-reset =
    .title = Сбросить { $panel }
    .prompt = Вы уверены, что хотите сбросить
    все настройки на этой панели?
    .confirm = Сбросить
    .cancel = Отмена
label-all-packages = Все пакеты
label-length-in-seconds = { $length } сек.
label-connecting-to-endpoint = Подключение к { $endpoint }...
label-could-not-connect-to-target = Не удалось подключиться к { $target }
label-unknown-error = Неизвестная ошибка
label-password-required = Требуется пароль
label-connection-failed = Ошибка подключения
notification-mod-switch-failed = Не удалось переключить мод.
dialog-rename-save =
    .title = Переименовать сохранение
    .prompt = Введите новое имя файла:
    .confirm = Переименовать
dialog-delete-save =
    .title = Удалить выбранное сохранение?
    .prompt = Удалить '{ $save }'.
    .confirm = Удалить
dialog-delete-all-saves =
    .title = Удалить все сохранения игры?
    .prompt =
    { $count ->
        [one] Удалить { $count } сохранение.
       *[other] Удалить { $count } сохранений.
    }
    .confirm = Удалить все
notification-save-deletion-failed = Не удалось удалить файл сохранения '{ $savePath }'. Смотрите логи для подробностей.
dialog-overwrite-save =
    .title = Перезаписать сохранение игры?
    .prompt = Перезаписать { $file }?
    .confirm = Перезаписать
label-loading-news = Загрузка новостей
label-news-retrieval-failed = Не удалось получить новости: { $message }
label-news-parsing-failed = Не удалось обработать новости: { $message }
label-author-datetime = автор { $author } в { $datetime }
label-all-maps = Все карты
label-no-matches = Нет совпадений
label-player-count = { $players ->
        [one] { $players } Игрок
       *[other] { $players } Игроков
    }
label-map-size-huge = Огромная
label-map-size-large = Большая
label-map-size-medium = В зависимости от контекста: "средний", "промежуточный", "умеренный"
label-map-size-small = Маленькая
label-map-searching-count = Поиск в OpenRA Resource Center по запросу
label-map-unavailable-count = { $count ->
        [one] { $count } карта не найдена в OpenRA Resource Center
       *[other] { $count } карт не найдено в OpenRA Resource Center
    }
notification-map-deletion-failed = Не удалось удалить карту '{ $map }'. Смотрите файл debug.log для подробностей.
dialog-delete-map =
    .title = Удалить карту
    .prompt = Удалить карту '{ $title }'?
    .confirm = Удалить
dialog-delete-all-maps =
    .title = Удалить карты
    .prompt = Удалить все карты на этой странице?
    .confirm = Удалить
options-order-maps =
    .player-count = Игроки
    .title = Название
    .date = Дата
    .size = Размер
button-mapchooser-system-maps-tab = Официальные карты
button-mapchooser-remote-maps-tab = Серверные карты
button-mapchooser-user-maps-tab = Пользовательские карты
button-mapchooser-generated-maps-tab = Сгенерировать карту
dialog-no-video =
    .title = Видео не установлено
    .prompt =
        Игровые видеоролики можно установить из
        меню "Управление контентом".
    .cancel = Назад
dialog-cant-play-video =
    .title = Не удалось воспроизвести видео
    .prompt = Что-то пошло не так во время воспроизведения видео.
    .cancel = Назад
label-sound-muted = Звук был отключен в настройках.
label-no-song-playing = Песня не воспроизводится
label-audio-muted = Звук отключен.
label-audio-unmuted = Звук включен.
label-loading-player-profile = Загрузка профиля игрока...
label-loading-player-profile-failed = Не удалось загрузить профиль игрока.
label-requires = Требуется: { $prerequisites }.
label-duration = Длительность: { $time }
options-replay-type =
    .singleplayer = Одиночная игра
    .multiplayer = Многопользовательская игра
options-winstate =
    .victory = Победа
    .defeat = Поражение
options-save-type =
    .autosave = Автосохранение
    .manual = Ручное сохранение
options-replay-date =
    .today = Сегодня
    .last-week = Последние 7 дней
    .last-fortnight = Последние 14 дней
    .last-month = Последние 30 дней
options-replay-duration =
    .very-short = Менее 5 мин
    .short = Короткие (10 мин)
    .medium = Средние (30 мин)
    .long = Длинные (60+ мин)
dialog-rename-replay =
    .title = Переименовать реплей
    .prompt = Введите новое имя файла:
    .confirm = Переименовать
dialog-delete-replay =
    .title = Удалить выбранный реплей?
    .prompt = Удалить реплей { $replay }?
    .confirm = Удалить
dialog-delete-all-replays =
    .title = Удалить все выбранные реплеи?
    .prompt =
    { $count ->
        [one] Удалить { $count } реплей.
       *[other] Удалить { $count } реплеев.
    }
    .confirm = Удалить все
notification-replay-deletion-failed = Не удалось удалить файл повтора '{ $file }'. Подробности смотрите в файле debug.log.
-incompatible-replay-recorded = Записано с использованием
dialog-incompatible-replay =
    .title = Несовместимый повтор
    .prompt = Не удалось прочитать метаданные повтора.
    .confirm = ОК
    .prompt-unknown-version = { -incompatible-replay-recorded } неизвестной версии.
    .prompt-unknown-mod = { -incompatible-replay-recorded } неизвестного мода.
    .prompt-unavailable-mod = { -incompatible-replay-recorded } недоступного мода: { $mod }.
    .prompt-incompatible-version = { -incompatible-replay-recorded } несовместимой версии:
    { $version }.
    .prompt-unavailable-map = { -incompatible-replay-recorded } недоступной карты:
    { $map }.
nothing-selected = Ничего не выбрано.
selected-units-across-screen = Выбрано { $units } юнитов на экране.
selected-units-across-map = Выбрано { $units } юнитов на карте.
label-internet-server-nat-A = Интернет-сервер (UPnP/NAT-PMP
label-internet-server-nat-B-enabled = Включено
label-internet-server-nat-B-not-supported = Не поддерживается
label-internet-server-nat-B-disabled = Отключено
label-internet-server-nat-C = ):
label-local-server = Локальный сервер:
dialog-server-creation-failed =
    .prompt = Не удалось начать прослушивание порта { $port }.
    .prompt-port-used = Проверьте, не используется ли этот порт.
    .prompt-error = Ошибка: "{ $message }" ({ $code }).
    .title = Ошибка создания сервера
    .cancel = Назад
label-players-online-count = { $players ->
        [one] { $players } игрок в сети
       *[other] Игроков в сети: { $players }
    }
label-search-status-failed = Не удалось запросить список серверов.
label-search-status-no-games = Игры не найдены. Попробуйте изменить фильтры.
label-no-server-selected = Сервер не выбран
label-map-status-searching = Поиск...
label-map-classification-unknown = Неизвестная карта
label-players-count = Игрок: { $players }
label-bots-count = { $bots ->
        [0] Нет ботов
        [one] Один бот
       *[other] Ботов: { $bots }
    }
label-players = Игроки
label-spectators = Зрители
label-spectators-count = { $spectators ->
        [0] Нет зрителей
        [one] Один зритель
       *[other] Зрителей: { $spectators }
    }
label-team-name = Команда { $team }
label-no-team = Без команды
label-playing = Играет
label-waiting = В ожидании
label-other-players-count = Один игрок / Другие игроки
label-in-progress-for = уже { $minutes } минут
label-password-protected = Защищено паролем
label-waiting-for-players = Идет поиск игроков
label-server-shutting-down = Сервер завершает работу
label-unknown-server-state = Неизвестное состояние сервера
notification-saved-screenshot = Скриншот сохранен: { $filename }
notification-invalid-command = { $name } не является допустимой командой.
tooltip-debug-command = Чит-команда: { $command }
description-combat-geometry = переключает отображение боевой геометрии.
description-render-geometry = отображение геометрии рендеринга
description-screen-map-overlay = переключает отображение карты на экране
description-depth-buffer = переключает отображение буфера глубины.
description-actor-tags-overlay = переключает отображение тегов объектов.
notification-invalid-cash-amount = Недопустимая сумма денег.
description-toggle-visibility = проверку видимости
description-give-cash = выдает стандартную или указанную сумму денег.
description-give-cash-all = выдает стандартную или указанную сумму денег всем игрокам и ИИ.
description-instant-building = включает/отключает мгновенное строительство
description-build-anywhere = переключает возможность строить где угодно.
description-unlimited-power = включает бесконечный режим / дает бесконечную энергию
description-enable-tech = разрешает/позволяет строить всё
description-fast-charge = перезарядку способностей саппорта
description-dev-cheat-all = за это
description-dev-crash = вызывает сбой игры.
description-levelup-actor = добавляет указанное количество уровней выбранным объектам.
description-player-experience = добавляет указанное количество опыта локальному игроку.
description-power-outage = вызывает 5-секундное отключение энергии у локального игрока.
description-grow-resources = выращивает ресурсы на карте.
description-clear-shroud = открывает всю карту.
description-reset-shroud = скрывает всю карту.
description-heal-selected-actors = персонажей
description-kill-selected-actors = персонажей
description-dispose-selected-actors = устраняет выбранных участников
notification-cheats-disabled = Читы отключены.
notification-available-commands = Доступные команды:
description-no-description = описание отсутствует.
description-help-description = предоставляет полезную информацию о различных командах.
description-pause-description = ставит или снимает игру с паузы.
description-surrender-description = уничтожить всё
notification-cheat-used = Чит использован: { $cheat } игроком { $player }{ $suffix }.
notification-cheat-enabled = кем
notification-cheat-disabled = отключен { $cheat } игроком { $player }
description-custom-terrain-debug-overlay = отладочный оверлей пользовательского ландшафта
description-cell-triggers-overlay = отображение триггеров скрипта
description-hpf-debug-overlay = иерархический оверлей поиска пути
description-path-debug-overlay = переключает визуализацию поиска пути.
description-terrain-geometry-overlay = переключает отображение геометрии ландшафта
description-actor-map-overlay = отображение объектов на карте
options-game-speed =
    .slowest = Самая медленная
    .slower = Медленная
    .normal = Нормальная
    .fast = Быстрая
    .faster = Очень быстрая
    .fastest = Самая быстрая

options-time-limit =
    .no-limit = Без ограничений
    .options =
        { $minutes ->
            [one] { $minutes } минута
            [few] { $minutes } минуты
           *[other] { $minutes } минут
        }

notification-time-limit-expired = Время истекло.
notification-added-actor = Добавлено: { $name } ({ $id })
notification-copied-tiles = Скопировано тайлов: { $tiles }
notification-copied-actors = Скопировано объектов: { $actors }
notification-copied-tiles-actors = Скопировано тайлов: { $tiles }, объектов: { $actors }
notification-selected-area = Выбрана область { $x },{ $y } ({ $width },{ $height })
notification-removed-area = Удалена область { $x },{ $y } ({ $width },{ $height })
notification-selected-actor = Выбранный актер
notification-cleared-selection = Выделение снято
notification-removed-actor = Удалено: { $name } ({ $id })
notification-removed-resource = Удалено: { $type }
notification-moved-actor = Объект { $id } перемещен из { $x1 },{ $y1 } в { $x2 },{ $y2 }
notification-added-resource = Добавлено { $count } клеток типа { $type }
notification-added-tile = Добавлен тайл { $id }
notification-filled-tile = Заполнено плиткой
notification-added-marker-tiles-markers =
    .red = красный
    .orange = оранжевый
    .yellow = желтый
    .green = зеленый
    .cyan = голубой
    .blue = синий
    .purple = фиолетовый
    .magenta = пурпурный
notification-added-marker-tiles = Добавлен { $count } { $type } маркерный тайл (тайлов)
notification-removed-marker-tiles = Удалено { $count } маркерных тайлов
notification-cleared-selected-marker-tiles = Очищено { $count } { $type } маркерных тайлов
notification-cleared-all-marker-tiles = тайлов маркеров
notification-opened = Открыто
mirror-mode =
    .none = Нет
    .flip = Отразить
    .rotate = Повернуть
notification-edited-actor = Изменен { $name } ({ $id })
notification-edited-actor-id = Изменен { $name } ({ $old-id }-> { $new-id })
notification-player-is-victorious = { $player } одерживает победу.
notification-player-is-defeated = { $player } терпит поражение.
notification-desync-compare-logs = Рассинхронизация на кадре { $frame }.
    Сравните syncreport.log с другими игроками.
label-win-state-won = Выиграл / Победил
label-win-state-lost = Утраченный / Потерянный
label-client-state-disconnected = Удален / Пропал
enumerated-bot-name = { $name } { $number ->
       *[zero] {""}
        [other] { $number }
    }
keycode-modifier =
    .alt = Alt
    .ctrl = Ctrl
    .meta = Meta
    .cmd = Cmd
    .shift = Shift
    .none = Нет
keycode =
    .unknown = Неизвестно
    .return = Return
    .escape = Escape
    .backspace = Backspace
    .tab = Tab
    .space = Пробел
    .exclaim = !
    .quotedbl = "
    .hash = #
    .percent = %
    .dollar = $
    .ampersand = &
    .quote = '
    .leftparen = (
    .rightparen = )
    .asterisk = *
    .plus = +
    .comma = ,
    .minus = -
    .period = .
    .slash = /
    .number_0 = 0
    .number_1 = 1
    .number_2 = 2
    .number_3 = 3
    .number_4 = 4
    .number_5 = 5
    .number_6 = 6
    .number_7 = 7
    .number_8 = 8
    .number_9 = 9
    .colon = :
    .semicolon = ;
    .less = <
    .equals = =
    .greater = >
    .question = ?
    .at = @
    .leftbracket = [
    .backslash = \
    .rightbracket = ]
    .caret = ^
    .underscore = _
    .backquote = `
    .a = A
    .b = B
    .c = C
    .d = D
    .e = E
    .f = F
    .g = G
    .h = H
    .i = I
    .j = J
    .k = K
    .l = L
    .m = M
    .n = N
    .o = O
    .p = P
    .q = Q
    .r = R
    .s = S
    .t = T
    .u = U
    .v = V
    .w = W
    .x = X
    .y = Y
    .z = Z
    .capslock = CapsLock
    .f1 = F1
    .f2 = F2
    .f3 = F3
    .f4 = F4
    .f5 = F5
    .f6 = F6
    .f7 = F7
    .f8 = F8
    .f9 = F9
    .f10 = F10
    .f11 = F11
    .f12 = F12
    .printscreen = PrintScreen
    .scrolllock = ScrollLock
    .pause = Pause
    .insert = Insert
    .home = Home
    .pageup = PageUp
    .delete = Delete
    .end = End
    .pagedown = PageDown
    .right = Вправо
    .left = Влево
    .down = Вниз
    .up = Вверх
    .numlockclear = Numlock
    .kp_divide = Numpad /
    .kp_multiply = Numpad *
    .kp_minus = Numpad -
    .kp_plus = Numpad +
    .kp_enter = Numpad Enter
    .kp_1 = Numpad 1
    .kp_2 = Numpad 2
    .kp_3 = Numpad 3
    .kp_4 = Numpad 4
    .kp_5 = Numpad 5
    .kp_6 = Numpad 6
    .kp_7 = Numpad 7
    .kp_8 = Numpad 8
    .kp_9 = Numpad 9
    .kp_0 = Numpad 0
    .kp_period = Numpad .
    .application = Application
    .power = Power
    .kp_equals = Numpad =
    .f13 = F13
    .f14 = F14
    .f15 = F15
    .f16 = F16
    .f17 = F17
    .f18 = F18
    .f19 = F19
    .f20 = F20
    .f21 = F21
    .f22 = F22
    .f23 = F23
    .f24 = F24
    .execute = Execute
    .help = Справка
    .menu = Меню
    .select = Выбрать
    .stop = Стоп
    .again = Снова
    .undo = Отменить
    .cut = Вырезать
    .copy = Копировать
    .paste = Вставить
    .find = Найти
    .mute = Без звука
    .volumeup = Громкость +
    .volumedown = Громкость -
    .kp_comma = Numpad ,
    .kp_equalsas400 = Numpad = (AS400)
    .alterase = AltErase
    .sysreq = SysReq
    .cancel = Отмена
    .clear = Очистить
    .prior = Prior
    .return2 = Return
    .separator = Разделитель
    .out = Out
    .oper = Oper
    .clearagain = Clear / Again
    .crsel = CrSel
    .exsel = ExSel
    .kp_00 = Numpad 00
    .kp_000 = Numpad 000
    .thousandsseparator = Разделитель тысяч
    .decimalseparator = Десятичный разделитель
    .currencyunit = Единица валюты
    .currencysubunit = Дробная единица валюты
    .kp_leftparen = Numpad (
    .kp_rightparen = Numpad )
    .kp_leftbrace = Numpad {"{"}
    .kp_rightbrace = Numpad {"}"}
    .kp_tab = Numpad Tab
    .kp_backspace = Numpad Backspace
    .kp_a = Numpad A
    .kp_b = Numpad B
    .kp_c = Numpad C
    .kp_d = Numpad D
    .kp_e = Numpad E
    .kp_f = Numpad F
    .kp_xor = Numpad XOR
    .kp_power = Numpad ^
    .kp_percent = Numpad %
    .kp_less = Numpad <
    .kp_greater = Numpad >
    .kp_ampersand = Numpad &
    .kp_dblampersand = Numpad &&
    .kp_verticalbar = Numpad |
    .kp_dblverticalbar = Numpad ||
    .kp_colon = Numpad :
    .kp_hash = Numpad #
    .kp_space = Numpad Пробел
    .kp_at = Numpad @
    .kp_exclam = Numpad !
    .kp_memstore = Numpad MemStore
    .kp_memrecall = Numpad MemRecall
    .kp_memclear = Numpad MemClear
    .kp_memadd = Numpad MemAdd
    .kp_memsubtract = Numpad MemSubtract
    .kp_memmultiply = Numpad MemMultiply
    .kp_memdivide = Numpad MemDivide
    .kp_plusminus = Numpad +/-
    .kp_clear = Numpad Очистить
    .kp_clearentry = Numpad ClearEntry
    .kp_binary = Numpad Бинарный
    .kp_octal = Numpad Восьмеричный
    .kp_decimal = Numpad Десятичный
    .kp_hexadecimal = Numpad Шестнадцатеричный
    .lctrl = Левый Ctrl
    .lshift = Левый Shift
    .lalt = Левый Alt
    .lgui = Левый GUI
    .rctrl = Правый Ctrl
    .rshift = Правый Shift
    .ralt = Правый Alt
    .rgui = Правый GUI
    .mode = ModeSwitch
    .audionext = Аудио: След.
    .audioprev = Аудио: Пред.
    .audiostop = Аудио: Стоп
    .audioplay = Аудио: Воспр.
    .audiomute = Аудио: Без звука
    .mediaselect = Выбор медиа
    .www = WWW
    .mail = Почта
    .calculator = Калькулятор
    .computer = Компьютер
    .ac_search = Поиск
    .ac_home = Домашняя страница
    .ac_back = Назад
    .ac_forward = Вперед
    .ac_stop = Стоп
    .ac_refresh = Обновить
    .ac_bookmarks = Закладки
    .brightnessdown = Яркость -
    .brightnessup = Яркость +
    .displayswitch = Перекл. дисплея
    .kbdillumtoggle = Подсветка клав.: Перекл.
    .kbdillumdown = Подсветка клав.: Меньше
    .kbdillumup = Подсветка клав.: Больше
    .eject = Извлечь
    .sleep = Сон
    .mouse4 = Мышь 4
    .mouse5 = Мышь 5
notification-map-generator-generated = Сгенерировано с помощью { $name }
dialog-notification-map-generator-failed =
    .title = Ошибка генерации карты
    .prompt = Подробности см. в debug.log.
    .cancel = Скрыть
notification-tiling-path-started = Началась укладка плитки
notification-tiling-path-updated = Обновленная схема укладки
notification-tiling-path-reset = Путь плитки отброшен
notification-tiling-path-painted = Расписная плиточная дорожка
