hotkey-context =
    .player = Игрок
    .spectator = Зритель
    .chat-input = Ввод чата
    .menu = Меню
    .editor = Редактор
hotkey-description-openteamchat = Открыть командный чат
hotkey-description-opengeneralchat = Открыть общий чат
hotkey-description-togglechatmode = Переключить режим чата
hotkey-description-autocomplete = Автодополнение
hotkey-description-controlgroupselect01 = Выбрать группу 1
hotkey-description-controlgroupselect02 = Выбрать группу 2
hotkey-description-controlgroupselect03 = Выбрать группу 3
hotkey-description-controlgroupselect04 = Выбрать группу 4
hotkey-description-controlgroupselect05 = Выбрать группу 5
hotkey-description-controlgroupselect06 = Выбрать группу 6
hotkey-description-controlgroupselect07 = Выбрать группу 7
hotkey-description-controlgroupselect08 = Выбрать группу 8
hotkey-description-controlgroupselect09 = Выбрать группу 9
hotkey-description-controlgroupselect10 = Выбрать группу 0
hotkey-description-controlgroupcreate01 = Создать группу 1
hotkey-description-controlgroupcreate02 = Создать группу 2
hotkey-description-controlgroupcreate03 = Создать группу 3
hotkey-description-controlgroupcreate04 = Создать группу 4
hotkey-description-controlgroupcreate05 = Создать группу 5
hotkey-description-controlgroupcreate06 = Создать группу 6
hotkey-description-controlgroupcreate07 = Создать группу 7
hotkey-description-controlgroupcreate08 = Создать группу 8
hotkey-description-controlgroupcreate09 = Создать группу 9
hotkey-description-controlgroupcreate10 = Создать группу 0
hotkey-description-controlgroupaddto01 = Добавить в группу 1
hotkey-description-controlgroupaddto02 = Добавить в группу 2
hotkey-description-controlgroupaddto03 = Добавить в группу 3
hotkey-description-controlgroupaddto04 = Добавить в группу 4
hotkey-description-controlgroupaddto05 = Добавить в группу 5
hotkey-description-controlgroupaddto06 = Добавить в группу 6
hotkey-description-controlgroupaddto07 = Добавить в группу 7
hotkey-description-controlgroupaddto08 = Добавить в группу 8
hotkey-description-controlgroupaddto09 = Добавить в группу 9
hotkey-description-controlgroupaddto10 = Добавить в группу 0
hotkey-description-controlgroupcombinewith01 = Объединить с группой 1
hotkey-description-controlgroupcombinewith02 = Объединить с группой 2
hotkey-description-controlgroupcombinewith03 = Объединить с группой 3
hotkey-description-controlgroupcombinewith04 = Объединить с группой 4
hotkey-description-controlgroupcombinewith05 = Объединить с группой 5
hotkey-description-controlgroupcombinewith06 = Объединить с группой 6
hotkey-description-controlgroupcombinewith07 = Объединить с группой 7
hotkey-description-controlgroupcombinewith08 = Объединить с группой 8
hotkey-description-controlgroupcombinewith09 = Объединить с группой 9
hotkey-description-controlgroupcombinewith10 = Объединить с группой 0
hotkey-description-controlgroupjumpto01 = Перейти к группе 1
hotkey-description-controlgroupjumpto02 = Перейти к группе 2
hotkey-description-controlgroupjumpto03 = Перейти к группе 3
hotkey-description-controlgroupjumpto04 = Перейти к группе 4
hotkey-description-controlgroupjumpto05 = Перейти к группе 5
hotkey-description-controlgroupjumpto06 = Перейти к группе 6
hotkey-description-controlgroupjumpto07 = Перейти к группе 7
hotkey-description-controlgroupjumpto08 = Перейти к группе 8
hotkey-description-controlgroupjumpto09 = Перейти к группе 9
hotkey-description-controlgroupjumpto10 = Перейти к группе 0
hotkey-description-removefromcontrolgroup = Удалить из группы контроля
hotkey-description-editorundo = Отменить
hotkey-description-editorredo = Повторить
hotkey-description-editorcopy = Копировать
hotkey-description-editorquicksave = Сохранить карту
hotkey-description-editorpaste = Вставить
hotkey-description-editordeleteselection = Удалить выделенное
hotkey-description-editorselecttab = Выбрать вкладку
hotkey-description-editortilestab = Вкладка тайлов
hotkey-description-editoroverlaystab = Вкладка оверлеев
hotkey-description-editoractorstab = Вкладка объектов
hotkey-description-editortoolstab = Вкладка инструментов
hotkey-description-editorhistorytab = Вкладка истории
hotkey-description-editorsettingstab = Вкладка настроек
hotkey-description-editortogglegridoverlay = Оверлей сетки
hotkey-description-editortogglebuildableoverlay = Слой зоны строительства
hotkey-description-editortogglemarkeroverlay = Оверлей маркеров
hotkey-description-cyclebase = Перейти к базе
hotkey-description-tolastevent = Перейти к последнему событию радара
hotkey-description-toselection = Перейти к выделенному
hotkey-description-selectallunits = Выбрать все боевые единицы
hotkey-description-selectunitsbytype = Выбрать войска по типу
hotkey-description-cycleharvesters = Следующий комбайн
hotkey-description-pause = Пауза / Продолжить
hotkey-description-sell = Режим продажи
hotkey-description-repair = Режим ремонта
hotkey-description-placebeacon = Разместить маяк
hotkey-description-cyclestatusbars = Смена отображения полос состояния
hotkey-description-togglemute = Включить/выключить звук
hotkey-description-toggleplayerstancecolor = Переключить цвета отношений
hotkey-description-takescreenshot = Сделать снимок экрана
hotkey-description-attackmove = Атака в движении
hotkey-description-stop = Стоп
hotkey-description-scatter = Рассредоточение
hotkey-description-deploy = Развернуть
hotkey-description-guard = Охранять
hotkey-description-stanceattackanything = Атаковать любого врага
hotkey-description-stancedefend = Защищать
hotkey-description-stancereturnfire = Открывать ответный огонь
hotkey-description-stanceholdfire = Прекратить огонь
hotkey-description-stopmusic = Остановить
hotkey-description-pausemusic = Пауза или Продолжить
hotkey-description-prevmusic = Предыдущий
hotkey-description-nextmusic = Следующий
hotkey-description-observercombinedview = Все игроки
hotkey-description-observerworldview = Отключить туман войны
hotkey-description-replayspeedslow = Медленная скорость
hotkey-description-replayspeedregular = Обычная скорость
hotkey-description-replayspeedfast = Высокая скорость
hotkey-description-replayspeedmax = Максимальная скорость
hotkey-description-statisticsnone = Отключить статистику
hotkey-description-statisticsbasic = Базовая статистика
hotkey-description-statisticseconomy = Экономическая статистика
hotkey-description-statisticsproduction = Статистика производства
hotkey-description-statisticssupportpowers = Статистика поддержки
hotkey-description-statisticscombat = Статистика боя
hotkey-description-statisticsarmy = Статистика армии
hotkey-description-statisticsgraph = График статистики
hotkey-description-statisticsarmygraph = График мощи армии
hotkey-description-cycleproductionbuildings = Следующее здание
hotkey-description-selectproductionbuilding = Текущее здание
hotkey-description-production01 = Слот 01
hotkey-description-production02 = Слот 02
hotkey-description-production03 = Слот 03
hotkey-description-production04 = Слот 04
hotkey-description-production05 = Слот 05
hotkey-description-production06 = Слот 06
hotkey-description-production07 = Слот 07
hotkey-description-production08 = Слот 08
hotkey-description-production09 = Слот 09
hotkey-description-production10 = Слот 10
hotkey-description-production11 = Слот 11
hotkey-description-production12 = Слот 12
hotkey-description-production13 = Слот 13
hotkey-description-production14 = Слот 14
hotkey-description-production15 = Слот 15
hotkey-description-production16 = Слот 16
hotkey-description-production17 = Слот 17
hotkey-description-production18 = Слот 18
hotkey-description-production19 = Слот 19
hotkey-description-production20 = Слот 20
hotkey-description-production21 = Слот 21
hotkey-description-production22 = Слот 22
hotkey-description-production23 = Слот 23
hotkey-description-production24 = Слот 24
hotkey-description-supportpower01 = Слот 01
hotkey-description-supportpower02 = Слот 02
hotkey-description-supportpower03 = Слот 03
hotkey-description-supportpower04 = Слот 04
hotkey-description-supportpower05 = Слот 05
hotkey-description-supportpower06 = Слот 06
hotkey-description-mapscrollup = Прокрутка вверх
hotkey-description-mapscrolldown = Прокрутка вниз
hotkey-description-mapscrollleft = Прокрутка влево
hotkey-description-mapscrollright = Прокрутка вправо
hotkey-description-mapjumptotopedge = Перейти к верхнему краю
hotkey-description-mapjumptobottomedge = Перейти к нижнему краю
hotkey-description-mapjumptoleftedge = Перейти к левому краю
hotkey-description-mapjumptorightedge = Перейти к правому краю
hotkey-description-mapbookmarksave01 = Записать закладку 1
hotkey-description-mapbookmarkrestore01 = Перейти к закладке 1
hotkey-description-mapbookmarksave02 = Записать закладку 2
hotkey-description-mapbookmarkrestore02 = Перейти к закладке 2
hotkey-description-mapbookmarksave03 = Записать закладку 3
hotkey-description-mapbookmarkrestore03 = Перейти к закладке 3
hotkey-description-mapbookmarksave04 = Записать закладку 4
hotkey-description-mapbookmarkrestore04 = Перейти к закладке 4
hotkey-description-zoomin = Приблизить
hotkey-description-zoomout = Отдалить
hotkey-description-resetzoom = Сбросить масштаб
hotkey-description-disableuserinterface = Отключить интерфейс пользователя
hotkey-description-disablealluserinterface = Отключить дополнительный интерфейс
