label-debug-panel-title = Читы
checkbox-debug-panel-instant-build = Мгновенное строительство
checkbox-debug-panel-enable-tech = Строить всё
checkbox-debug-panel-build-anywhere = Строить где угодно
checkbox-debug-panel-unlimited-power = Неограниченная энергия
checkbox-debug-panel-instant-charge = Мгновенная зарядка
checkbox-debug-panel-disable-visibility-checks = Отключить проверку видимости
button-debug-panel-give-cash = Дать $20,000
button-debug-panel-give-cash-all = Раздать деньги всем
button-debug-panel-heal-selected = Вылечить выбранное
button-debug-panel-dispose-selected = Удалить выбранное
button-debug-panel-grow-resources = Добавить ресурсы
button-debug-panel-kill-selected = Убить выбранное
button-debug-panel-clear-shroud = Убрать туман войны
button-debug-panel-reset-shroud = Сбросить туман войны
button-debug-panel-level-up = Повысить уровень
button-debug-panel-player-experience = Опыт игрока
label-debug-panel-selection-title = Выбор
label-debug-panel-visualizations-title = Визуализация
checkbox-debug-panel-show-unit-paths = Показать пути войск
checkbox-debug-panel-show-customterrain-overlay = Показать особый рельеф
checkbox-debug-panel-show-actor-tags = Показать теги объектов
checkbox-debug-panel-show-combatoverlay = Показать геометрию боя
checkbox-debug-panel-show-geometry = Показать геометрию рендеринга
checkbox-debug-panel-show-terrain-overlay = Показать геометрию рельефа
checkbox-debug-panel-show-celltrigger-overlay = Показать триггеры ячеек
checkbox-debug-panel-show-actormap-overlay = Показать карту объектов
checkbox-debug-panel-show-screenmap = Показать карту экрана
checkbox-debug-panel-show-hpf-overlay = Показать оверлей HPF
