## rules.yaml
briefing = LANDCOM 16 HQS.
    TOP SECRET.
    TO: FIELD COMMANDER A9
    
    INTERCEPTION OF SOVIET COMMUNIQUE INDICATES THAT THEIR IRON CURTAIN RESEARCH WAS SET BACK BY ESPIONAGE. EXCELLENT WORK, COMMANDER!
    
    COMMUNIQUE WAS TRACED BACK TO A SECRET SOVIET BASE IN BORNHOLM. INVESTIGATE POSSIBLE CONNECTION WITH IRON CURTAIN RESEARCH. CAPTURE RADAR CENTER AND DESTROY SUB PRODUCTION CAPABILITY.
    
    CONFIRMATION CODE 1138.
    
    TRANSMISSION ENDS.
