objective-failed = Задание провалено
objective-completed = Задача выполнена
primary = Основные
secondary = Второстепенные
new-primary-objective = Новая основная задача
new-secondary-objective = Новая второстепенная задача
mentat = Ментат
harvested-resources = Собранные ресурсы: { $harvested }/{ $goal }
harvest-spice = Соберите пряность стоимостью { $spice } соляриев.
not-enough-silos = Недостаточно места в хранилищах для пряности
build-concrete = Постройте бетонный фундамент перед возведением построек.
build-wind-trap = Постройте ветроуловитель для выработки энергии.
build-refinery = Постройте обогатитель для сбора пряности.
build-silo = Постройте хранилище для хранения дополнительной пряности.
eliminate-harkonnen-units-reinforcements = Уничтожьте все войска Харконненов и подкрепления в этом районе.
harkonnen-annihilated = Харконнены были уничтожены!
destroy-harkonnen-forces = Уничтожьте все силы Харконненов.
ordos-annihilated = Ордосы были уничтожены!
upgrade-barracks-light-factory = Улучшите бараки и лёгкий завод
eliminate-ordos-units-reinforcements = Уничтожьте все силы Ордосов и подкрепления в этом районе.
destroy-harkonnen = Уничтожьте Харконненов.
fremen-leader = Лидер Свободных
sietch-integrity = Структурная целостность ситча: { $integrity }%
protect-fremen-sietch = Защитите ситч Свободных.
keep-sietch-intact = Сохраните ситч целым на { $integrity }%!
fremen-sietch-southeast = На юго-востоке обнаружен ситч Свободных.
harkonnen-units-approaching = Приближаются войска Харконненов!
sietch-destroyed = Ситч уничтожен!
fremen-sietch-under-attack = Ситч Свободных атакован!
smugglers-annihilated = Контрабандисты были уничтожены!
incoming-mercenary-force = Приближаются враждебные силы наемников.
contraband-has-arrived = Контрабанда прибыла!
contraband-confiscated = Контрабанда прибыла и была конфискована.
contraband-not-confiscated = Контрабанда прибыла, но ее конфискация невозможна из-за сильной защиты космопорта.
contraband-arrives-in = Контрабанда прибудет через { $time }
capture-barracks-sietch-tabr = Захватите бараки в ситче Табр.
annihilate-harkonnen-units-reinforcements = Уничтожьте все подкрепления Харконненов.
capture-smuggler-starport-confiscate-contraband = Захватите космопорт контрабандистов и
    конфискуйте контрабанду.
contraband-approaching-starport-north-in = Контрабанда приближается к космопорту на севере через { $time }
starport-destroyed-no-contraband = Космопорт уничтожен! Контрабанда не может приземлиться.
do-not-destroy-starport = Не уничтожайте космопорт!
defend-captured-starport = Защищайте захваченный космопорт.
do-not-destroy-barracks = Не уничтожайте бараки!
hostages-released = Заложники освобождены!
stay-away-from-starport = Держитесь подальше от нашего космопорта.
smuggler-leader = Лидер контрабандистов.
were-warned-will-pay = Вас предупреждали. Теперь вы за это заплатите.
destroy-smugglers-mercenaries = Уничтожьте контрабандистов и их наемников.
capture-harkonnen-barracks-release-hostages = Захватите бараки Харконненов, чтобы освободить заложников.
use-engineer-hint = Используйте инженеров для восстановления уничтоженной техники.
eliminate-atreides-units-reinforcements = Уничтожьте все силы Атрейдесов и подкрепления в этом районе.
atreides-annihilated = Атрейдесы были уничтожены!
destroy-atreides-forces = Уничтожьте все силы Атрейдесов.
destroy-atreides = Уничтожьте Атрейдесов.
fremen-annihilated = Свободные были уничтожены!
destroy-fremen = Уничтожьте Свободных.
fremen-spotted-north-southwest = К северу и юго-западу замечены скопления Свободных.
imperial-ships-penetrating-defense-grid = Имперские корабли прорывают защитную сеть!
enemy-carryall-drop-detected = Обнаружена высадка вражеского транспортника!
keep-modified-outpost-intact = Сохраните модифицированный аванпост целым.
protect-outpost = Защитите заставу от нападения.
destroy-imperial-forces = Уничтожьте имперские силы.
emperor-annihilated = Император был уничтожен!
destroy-ordos = Уничтожьте Ордосов.
ixian-transports-detected = Обнаружены иксианские транспорты.
capture-destroy-ordos-starport = Захватите или уничтожьте космопорт Ордосов.
smuggler-warning-harkonnen = Не лезьте не в свое дело, Харконнены.
smuggler-warning-ordos = Не лезьте не в свое дело, Ордосы.
smugglers-now-hostile = Теперь контрабандисты враждебны!
high-tech-factory-neutralized-imperial-reinforcements = Высокотехнологичный завод нейтрализован! Атрейдесы отрезаны от имперских подкреплений!
capture-atreides-construction-yard-south = Захватите сборочный цех Атрейдесов на юге.
destroy-corrino = Уничтожьте Коррино.
destroy-atreides-high-tech-factory-imperial-reinforcements = Уничтожьте высокотехнологичный завод Атрейдесов, чтобы отрезать их от имперских подкреплений.
atreides-hostile = Теперь Атрейдесы враждебны!
mercenaries-annihilated = Наемники были уничтожены!
ally-mercenaries = Убедите наемников сражаться на стороне Дома Харконнен.
mercenary-leader-captured-allied = Лидер захвачен. Наемников убедили сражаться за Дом Харконнен.
cannot-stand-harkonnen-must-become-neutral = Мы не можем противостоять Харконненам. Мы должны сохранять нейтралитет.
atreides-commander = Командир Атрейдесов
build-deploy-mcv = Постройте и разверните МСЦ для создания строительной площадки.
husk-reclaimed-harkonnen = Мы подобрали обломки Атрейдесов с поля боя.
engineers-hint = Наши инженеры, возможно, найдут им применение.
outpost-not-captured-destroyed = Не допустите захвата или разрушения заставы.
capture-smuggler-outpost = Захватите заставу контрабандистов.
do-not-destroy-outpost = Не разрушайте заставу!
warning-large-force-approaching = ВНИМАНИЕ: Приближаются крупные силы противника!
capture-atreides-starport-establish-base = Захватите космопорт Атрейдесов и создайте базу.
ixian-reinforcements-arrived = Иксианские подкрепления прибыли!
deliveries-arriving-massive-reinforcements = Начинают прибывать грузы; ожидаются крупные подкрепления!
initial-reinforcements-arrive-in = Первые подкрепления прибудут через { $time }
additional-reinforcements-arrive-in = Дополнительные подкрепления прибудут через { $time }
defend-starport = Защитите космопорт.
ixian-reinforcements-in = Первая партия иксианских подкреплений прибудет через { $time }
enemy-reinforcements-arrived = Вражеские подкрепления прибыли.
