## rules.yaml
briefing = GDI influence in this area is running rampant. Establish a well positioned strike base, and clean the area out. A nearby town may provide a suitable location for your base, provided the occupants are "persuaded" to move....
