Container@INPUT_PANEL:
	Logic: InputSettingsLogic
	Width: PARENT_RIGHT
	Height: PARENT_BOTTOM
	Children:
		ScrollPanel@SETTINGS_SCROLLPANEL:
			Width: PARENT_RIGHT
			Height: PARENT_BOTTOM
			CollapseHiddenChildren: True
			TopBottomSpacing: 5
			ItemSpacing: 10
			Children:
				Background@INPUT_SECTION_HEADER:
					X: 5
					Width: PARENT_RIGHT - 24 - 10
					Height: 13
					Background: separator
					ClickThrough: True
					Children:
						Label@LABEL:
							Width: PARENT_RIGHT
							Height: PARENT_BOTTOM
							Font: TinyBold
							Align: Center
							Text: label-input-section-header-label
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 50
					Children:
						Container@MOUSE_CONTROL_CONTAINER:
							X: 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Label@MOUSE_CONTROL_LABEL:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: label-mouse-control-container-mouse-control-label
								DropDownButton@MOUSE_CONTROL_DROPDOWN:
									Y: 25
									Width: PARENT_RIGHT
									Height: 25
									Font: Regular
						Container@ZOOM_MODIFIER_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Label@ZOOM_MODIFIER_LABEL:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: label-zoom-modifier-container-zoom-modifier-label
								DropDownButton@ZOOM_MODIFIER:
									Y: 25
									Width: PARENT_RIGHT
									Height: 25
									Font: Regular
						Container@MOUSE_CONTROL_DESC_CLASSIC:
							X: 10
							Y: 55
							Width: PARENT_RIGHT
							Children:
								LabelWithHighlight@DESC_SELECTION:
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-classic-desc-selection
								LabelWithHighlight@DESC_COMMANDS:
									Y: 17
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-classic-desc-commands
								LabelWithHighlight@DESC_BUILDIGS:
									Y: 34
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-classic-desc-buildigs
								LabelWithHighlight@DESC_SUPPORT:
									Y: 51
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-classic-desc-support
								LabelWithHighlight@DESC_ZOOM:
									Y: 68
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-classic-desc-zoom
								LabelWithHighlight@DESC_ZOOM_MODIFIER:
									Y: 68
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-classic-desc-zoom-modifier
								LabelWithHighlight@DESC_SCROLL_RIGHT:
									Y: 85
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-classic-desc-scroll-right
								LabelWithHighlight@DESC_SCROLL_MIDDLE:
									Y: 85
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-classic-desc-scroll-middle
								Label@DESC_EDGESCROLL:
									X: 9
									Y: 102
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-classic-desc-edgescroll
						Container@MOUSE_CONTROL_DESC_MODERN:
							X: 10
							Y: 55
							Width: PARENT_RIGHT / 2 - 20
							Children:
								LabelWithHighlight@DESC_SELECTION:
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-modern-desc-selection
								LabelWithHighlight@DESC_COMMANDS:
									Y: 17
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-modern-desc-commands
								LabelWithHighlight@DESC_BUILDIGS:
									Y: 34
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-modern-desc-buildigs
								LabelWithHighlight@DESC_SUPPORT:
									Y: 51
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-modern-desc-support
								LabelWithHighlight@DESC_ZOOM:
									Y: 68
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-modern-desc-zoom
								LabelWithHighlight@DESC_ZOOM_MODIFIER:
									Y: 68
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-modern-desc-zoom-modifier
								LabelWithHighlight@DESC_SCROLL_RIGHT:
									Y: 85
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-modern-desc-scroll-right
								LabelWithHighlight@DESC_SCROLL_MIDDLE:
									Y: 85
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-modern-desc-scroll-middle
								Label@DESC_EDGESCROLL:
									X: 9
									Y: 102
									Height: 16
									Font: Small
									Text: label-mouse-control-desc-modern-desc-edgescroll
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 20
					Children:
						Container@EDGESCROLL_CHECKBOX_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@EDGESCROLL_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: checkbox-edgescroll-checkbox-container-edgescroll-checkbox
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 20
					Children:
						Container@ALTERNATE_SCROLL_CHECKBOX_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@ALTERNATE_SCROLL_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: checkbox-alternate-scroll-checkbox-container-alternate-scroll-checkbox
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 20
					Children:
						Container@LOCKMOUSE_CHECKBOX_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@LOCKMOUSE_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: checkbox-lockmouse-checkbox-container-lockmouse-checkbox
				Container@SPACER:
					Height: 30
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 50
					Children:
						Container@MOUSE_SCROLL_TYPE_CONTAINER:
							X: 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Label@MOUSE_SCROLL_TYPE_LABEL:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: label-mouse-scroll-type-container-mouse-scroll-type-label
								DropDownButton@MOUSE_SCROLL_TYPE_DROPDOWN:
									Y: 25
									Width: PARENT_RIGHT
									Height: 25
									Font: Regular
						Container@SCROLLSPEED_SLIDER_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Label@SCROLL_SPEED_LABEL:
									Width: PARENT_RIGHT
									Height: 20
									Text: label-scrollspeed-slider-container-scroll-speed-label
								Slider@SCROLLSPEED_SLIDER:
									Y: 25
									Width: PARENT_RIGHT
									Height: 20
									Ticks: 7
									MinimumValue: 10
									MaximumValue: 50
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 50
					Children:
						Container@ZOOMSPEED_SLIDER_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Label@ZOOM_SPEED_LABEL:
									Width: PARENT_RIGHT
									Height: 20
									Text: label-zoomspeed-slider-container-zoom-speed-label
								ExponentialSlider@ZOOMSPEED_SLIDER:
									Y: 25
									Width: PARENT_RIGHT
									Height: 20
									Ticks: 7
									MinimumValue: 0.01
									MaximumValue: 0.4
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 50
					Children:
						Container@UI_SCROLLSPEED_SLIDER_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Label@UI_SCROLL_SPEED_LABEL:
									Width: PARENT_RIGHT
									Height: 20
									Text: label-ui-scrollspeed-slider-container-ui-scroll-speed-label
								Slider@UI_SCROLLSPEED_SLIDER:
									Y: 25
									Width: PARENT_RIGHT
									Height: 20
									Ticks: 7
									MinimumValue: 1
									MaximumValue: 100

