#!/bin/bash
# Copyright 2007-2010 The OpenRA Developers (see AUTHORS)
# This file is part of OpenRA, which is free software. It is made 
# available to you under the terms of the GNU General Public License
# as published by the Free Software Foundation. For more information,
# see LICENSE.

echo "Launching OpenRA from $1"
cd $1
mono --debug OpenRA.Game.exe Graphics.Renderer=Gl SupportDir=~/Library/"Application Support"/OpenRA ${@:2}