## rules.yaml
briefing = INCOMING REPORT:
    
    Commander! The Soviets have rendered our forces useless...
    Reports indicate Soviet reinforcements are coming to finish us off... The situation looks bleak...
