hotkey-context =
    .player = Player
    .spectator = Spectator
    .chat-input = Chat Input
    .menu = Menu
    .editor = Editor

## chat.yaml
hotkey-description-openteamchat = Open Team Chat
hotkey-description-opengeneralchat = Open General Chat
hotkey-description-togglechatmode = Toggle Chat Mode
hotkey-description-autocomplete = Autocomplete

## control-groups.yaml
hotkey-description-controlgroupselect01 = Select group 1
hotkey-description-controlgroupselect02 = Select group 2
hotkey-description-controlgroupselect03 = Select group 3
hotkey-description-controlgroupselect04 = Select group 4
hotkey-description-controlgroupselect05 = Select group 5
hotkey-description-controlgroupselect06 = Select group 6
hotkey-description-controlgroupselect07 = Select group 7
hotkey-description-controlgroupselect08 = Select group 8
hotkey-description-controlgroupselect09 = Select group 9
hotkey-description-controlgroupselect10 = Select group 0
hotkey-description-controlgroupcreate01 = Create group 1
hotkey-description-controlgroupcreate02 = Create group 2
hotkey-description-controlgroupcreate03 = Create group 3
hotkey-description-controlgroupcreate04 = Create group 4
hotkey-description-controlgroupcreate05 = Create group 5
hotkey-description-controlgroupcreate06 = Create group 6
hotkey-description-controlgroupcreate07 = Create group 7
hotkey-description-controlgroupcreate08 = Create group 8
hotkey-description-controlgroupcreate09 = Create group 9
hotkey-description-controlgroupcreate10 = Create group 0
hotkey-description-controlgroupaddto01 = Add to group 1
hotkey-description-controlgroupaddto02 = Add to group 2
hotkey-description-controlgroupaddto03 = Add to group 3
hotkey-description-controlgroupaddto04 = Add to group 4
hotkey-description-controlgroupaddto05 = Add to group 5
hotkey-description-controlgroupaddto06 = Add to group 6
hotkey-description-controlgroupaddto07 = Add to group 7
hotkey-description-controlgroupaddto08 = Add to group 8
hotkey-description-controlgroupaddto09 = Add to group 9
hotkey-description-controlgroupaddto10 = Add to group 0
hotkey-description-controlgroupcombinewith01 = Combine with group 1
hotkey-description-controlgroupcombinewith02 = Combine with group 2
hotkey-description-controlgroupcombinewith03 = Combine with group 3
hotkey-description-controlgroupcombinewith04 = Combine with group 4
hotkey-description-controlgroupcombinewith05 = Combine with group 5
hotkey-description-controlgroupcombinewith06 = Combine with group 6
hotkey-description-controlgroupcombinewith07 = Combine with group 7
hotkey-description-controlgroupcombinewith08 = Combine with group 8
hotkey-description-controlgroupcombinewith09 = Combine with group 9
hotkey-description-controlgroupcombinewith10 = Combine with group 0
hotkey-description-controlgroupjumpto01 = Jump to group 1
hotkey-description-controlgroupjumpto02 = Jump to group 2
hotkey-description-controlgroupjumpto03 = Jump to group 3
hotkey-description-controlgroupjumpto04 = Jump to group 4
hotkey-description-controlgroupjumpto05 = Jump to group 5
hotkey-description-controlgroupjumpto06 = Jump to group 6
hotkey-description-controlgroupjumpto07 = Jump to group 7
hotkey-description-controlgroupjumpto08 = Jump to group 8
hotkey-description-controlgroupjumpto09 = Jump to group 9
hotkey-description-controlgroupjumpto10 = Jump to group 0
hotkey-description-removefromcontrolgroup = Remove from control group

## editor.yaml
hotkey-description-editorundo = Undo
hotkey-description-editorredo = Redo
hotkey-description-editorcopy = Copy
hotkey-description-editorquicksave = Save Map
hotkey-description-editorpaste = Paste
hotkey-description-editordeleteselection = Delete Selection
hotkey-description-editorselecttab = Select Tab
hotkey-description-editortilestab = Tiles Tab
hotkey-description-editoroverlaystab = Overlays Tab
hotkey-description-editoractorstab = Actors Tab
hotkey-description-editortoolstab = Tools Tab
hotkey-description-editorhistorytab = History Tab
hotkey-description-editorsettingstab = Settings Tab
hotkey-description-editortogglegridoverlay = Grid Overlay
hotkey-description-editortogglebuildableoverlay = Buildable Terrain Overlay
hotkey-description-editortogglemarkeroverlay = Marker Layer Overlay

## game.yaml
hotkey-description-cyclebase = Jump to base
hotkey-description-tolastevent = Jump to last radar event
hotkey-description-toselection = Jump to selection
hotkey-description-selectallunits = Select all combat units
hotkey-description-selectunitsbytype = Select units by type
hotkey-description-cycleharvesters = Cycle Harvesters
hotkey-description-pause = Pause / Unpause
hotkey-description-sell = Sell mode
hotkey-description-repair = Repair mode
hotkey-description-placebeacon = Place beacon
hotkey-description-cyclestatusbars = Cycle status bars display
hotkey-description-togglemute = Toggle audio mute
hotkey-description-toggleplayerstancecolor = Toggle player stance colors
hotkey-description-takescreenshot = Take screenshot
hotkey-description-attackmove = Attack Move
hotkey-description-stop = Stop
hotkey-description-scatter = Scatter
hotkey-description-deploy = Deploy
hotkey-description-guard = Guard
hotkey-description-stanceattackanything = Attack anything
hotkey-description-stancedefend = Defend
hotkey-description-stancereturnfire = Return fire
hotkey-description-stanceholdfire = Hold fire
hotkey-description-stopmusic = Stop
hotkey-description-pausemusic = Pause or Resume
hotkey-description-prevmusic = Previous
hotkey-description-nextmusic = Next

## observer.yaml
hotkey-description-observercombinedview = All Players
hotkey-description-observerworldview = Disable Shroud
hotkey-description-replayspeedslow = Slow speed
hotkey-description-replayspeedregular = Regular speed
hotkey-description-replayspeedfast = Fast speed
hotkey-description-replayspeedmax = Maximum speed
hotkey-description-statisticsnone = Disable statistics
hotkey-description-statisticsbasic = Basic statistics
hotkey-description-statisticseconomy = Economy statistics
hotkey-description-statisticsproduction = Production statistics
hotkey-description-statisticssupportpowers = Support Power statistics
hotkey-description-statisticscombat = Combat statistics
hotkey-description-statisticsarmy = Army statistics
hotkey-description-statisticsgraph = Statistics graph
hotkey-description-statisticsarmygraph = Army value graph

## production-common.yaml
hotkey-description-cycleproductionbuildings = Next facility
hotkey-description-selectproductionbuilding = Current facility
hotkey-description-production01 = Slot 01
hotkey-description-production02 = Slot 02
hotkey-description-production03 = Slot 03
hotkey-description-production04 = Slot 04
hotkey-description-production05 = Slot 05
hotkey-description-production06 = Slot 06
hotkey-description-production07 = Slot 07
hotkey-description-production08 = Slot 08
hotkey-description-production09 = Slot 09
hotkey-description-production10 = Slot 10
hotkey-description-production11 = Slot 11
hotkey-description-production12 = Slot 12
hotkey-description-production13 = Slot 13
hotkey-description-production14 = Slot 14
hotkey-description-production15 = Slot 15
hotkey-description-production16 = Slot 16
hotkey-description-production17 = Slot 17
hotkey-description-production18 = Slot 18
hotkey-description-production19 = Slot 19
hotkey-description-production20 = Slot 20
hotkey-description-production21 = Slot 21
hotkey-description-production22 = Slot 22
hotkey-description-production23 = Slot 23
hotkey-description-production24 = Slot 24

## supportpowers.yaml
hotkey-description-supportpower01 = Slot 01
hotkey-description-supportpower02 = Slot 02
hotkey-description-supportpower03 = Slot 03
hotkey-description-supportpower04 = Slot 04
hotkey-description-supportpower05 = Slot 05
hotkey-description-supportpower06 = Slot 06

## viewport.yaml
hotkey-description-mapscrollup = Scroll up
hotkey-description-mapscrolldown = Scroll down
hotkey-description-mapscrollleft = Scroll left
hotkey-description-mapscrollright = Scroll right
hotkey-description-mapjumptotopedge = Jump to top edge
hotkey-description-mapjumptobottomedge = Jump to bottom edge
hotkey-description-mapjumptoleftedge = Jump to left edge
hotkey-description-mapjumptorightedge = Jump to right edge
hotkey-description-mapbookmarksave01 = Record bookmark 1
hotkey-description-mapbookmarkrestore01 = Jump to bookmark 1
hotkey-description-mapbookmarksave02 = Record bookmark 2
hotkey-description-mapbookmarkrestore02 = Jump to bookmark 2
hotkey-description-mapbookmarksave03 = Record bookmark 3
hotkey-description-mapbookmarkrestore03 = Jump to bookmark 3
hotkey-description-mapbookmarksave04 = Record bookmark 4
hotkey-description-mapbookmarkrestore04 = Jump to bookmark 4
hotkey-description-zoomin = Zoom in
hotkey-description-zoomout = Zoom out
hotkey-description-resetzoom = Reset zoom
