## ingame-debug.yaml
label-debug-panel-title = Cheats
checkbox-debug-panel-instant-build = Instant Build Speed
checkbox-debug-panel-enable-tech = Build Everything
checkbox-debug-panel-build-anywhere = Build Anywhere
checkbox-debug-panel-unlimited-power = Unlimited Power
checkbox-debug-panel-instant-charge = Instant Charge Time
checkbox-debug-panel-disable-visibility-checks = Disable Visibility Checks
button-debug-panel-give-cash = Give $20,000
button-debug-panel-give-cash-all = Give Cash All
button-debug-panel-dispose-selected = Dispose Selected
button-debug-panel-grow-resources = Grow Resources
button-debug-panel-kill-selected = Kill Selected
button-debug-panel-clear-shroud = Clear Shroud
button-debug-panel-reset-shroud = Reset Shroud
button-debug-panel-level-up = Level Up
button-debug-panel-player-experience = Player Experience
label-debug-panel-selection-title = Selection
label-debug-panel-visualizations-title = Visualizations
checkbox-debug-panel-show-unit-paths = Show Unit Paths
checkbox-debug-panel-show-customterrain-overlay = Show Custom Terrain
checkbox-debug-panel-show-actor-tags = Show Actor Tags
checkbox-debug-panel-show-combatoverlay = Show Combat Geometry
checkbox-debug-panel-show-geometry = Show Render Geometry
checkbox-debug-panel-show-terrain-overlay = Show Terrain Geometry
checkbox-debug-panel-show-celltrigger-overlay = Show Cell Triggers
checkbox-debug-panel-show-actormap-overlay = Show Actor Map
checkbox-debug-panel-show-screenmap = Show Screen Map
checkbox-debug-panel-show-hpf-overlay = Show HPF Overlay
