Background@SETTINGS_MENU:
	Logic:SettingsMenuLogic
	X:(WINDOW_RIGHT - WIDTH)/2
	Y:(WINDOW_BOTTOM- HEIGHT)/2
	Width: 550
	Height: 350
	Children:
		Label@SETTINGS_LABEL_TITLE:
			X:0
			Y:20
			Width:450
			Height:25
			Text:Настройки
			Align:Center
			Font:Bold
		Button@BUTTON_CLOSE:
			X:PARENT_RIGHT - 180
			Y:PARENT_BOTTOM - 45
			Width:160
			Height:25
			Text:Закрыть
			Font:Bold
			Key:escape
		Container@TAB_CONTAINER:
			X:0
			Y:50
			Width:PARENT_RIGHT
			Height:25
			Children:
				Button@GENERAL:
					X:45
					Y:0
					Width:90
					Height:25
					Text:Общие
					Font:Bold
				Button@AUDIO:
					X:135
					Y:0
					Width:90
					Height:25
					Text:Звук
					Font:Bold
				Button@DISPLAY:
					X:225
					Y:0
					Width:90
					Height:25
					Text:Дисплей
					Font:Bold
				Button@DEBUG:
					X:315
					Y:0
					Width:90
					Height:25
					Text:Отладка
					Font:Bold
		Container@GENERAL_PANE:
			X:37
			Y:100
			Width:PARENT_RIGHT - 37
			Height:PARENT_BOTTOM - 100
			Visible: true
			Children:
				Label@SETTINGS_PLAYER_NAME:
					X:0
					Y:10
					Text: Имя игрока:
				TextField@NAME:
					Text:Имя
					Width:139
					Height:25
					X:90
					Y:0
					MaxLength:16
				Checkbox@EDGE_SCROLL:
					X:0
					Y:30
					Width:200
					Height:20
					Text: Включить выход за пределы
				Label@EDGE_SCROLL_AMOUNT_LABEL:
					X:0
					Y:70
					Text: Скорость перемещения
				Slider@EDGE_SCROLL_AMOUNT:
					X:180
					Y:60
					Width:250
					Height:20
					Ticks:5
					MinimumValue: 10
					MaximumValue: 50
				Checkbox@INVERSE_SCROLL:
					X:0
					Y:90
					Width:200
					Height:20
					Text: Инвентировать перемещние мышью
				Checkbox@TEAMCHAT_TOGGLE:
					X:0
					Y:120
					Width:200
					Height:20
					Text: Shift-Enter переключает на командный чат
				Checkbox@SHOW_SHELLMAP:
					X:0
					Y:150
					Width:200
					Height:20
					Text: Показывать Карту в меню
		Container@AUDIO_PANE:
			X:37
			Y:100
			Width:PARENT_RIGHT - 37
			Height:PARENT_BOTTOM - 100
			Visible: false
			Children:
				Label@SOUND_VOLUME_LABEL:
					X:0
					Y:10
					Text: Громкость звука
				Slider@SOUND_VOLUME:
					X:200
					Y:0
					Width:250
					Height:20
					Ticks:5
				Label@MUSIC_VOLUME_LABEL:
					X:0
					Y:40
					Text: Громкость музыки
				Slider@MUSIC_VOLUME:
					X:200
					Y:30
					Width:250
					Height:20
					Ticks:5
				Label@SOUND_TICK_TYPE_LABEL:
					X:0
					Y:70
					Text: Звук растраты денег
				DropDownButton@CASH_TICK_TYPE:
					X:200
					Y:60
					Width:250
					Height:25
					Font:Regular
					Text:Экстремальный
		Container@DISPLAY_PANE:
			X:37
			Y:100
			Width:PARENT_RIGHT - 37
			Height:PARENT_BOTTOM - 100
			Visible: false
			Children:
				Label@RENDERER_LABEL:
					X:0
					Y:0
					Width:75
					Height:25
					Text:Рендерер:
				DropDownButton@GRAPHICS_RENDERER:
					X:80
					Y:1
					Width:120
					Height:25
					Font:Regular
					Text:OpenGL
				Label@MODE_LABEL:
					X:0
					Y:30
					Width:45
					Height:25
					Text:Режим:
				DropDownButton@MODE_DROPDOWN:
					X:50
					Y:30
					Width:170
					Height:25
					Font:Regular
					Text:Оконный
				Container@WINDOW_RESOLUTION:
					X:225
					Y:30
					Children:
						Label@At:
							Text:@
							Font:Bold
							Y:0-1
							Height:25
							Width:25
							Align:Center
						TextField@WINDOW_WIDTH:
							X:25
							Width:45
							Height:25
							MaxLength:5
						Label@X:
							Text:x
							Font:Bold
							X:70
							Y:0-1
							Height:25
							Width:15
							Align:Center
						TextField@WINDOW_HEIGHT:
							X:85
							Width:45
							Height:25
							MaxLength:5
				Label@VIDEO_DESC:
					Y:60
					Width:PARENT_RIGHT
					Height:25
					Font:Tiny
					Align:Center
					Text:Изменения Рендерера/Режима/Разрешения будет осуществлено после перезагрузки игры.
				Checkbox@PIXELDOUBLE_CHECKBOX:
					Y:90
					Width:200
					Height:20
					Font:Regular
					Text:Включить удвоение пикселей
		Container@DEBUG_PANE:
			X:37
			Y:100
			Width:PARENT_RIGHT - 37
			Height:PARENT_BOTTOM - 100
			Visible: false
			Children:
				Checkbox@PERFDEBUG_CHECKBOX:
					X:0
					Y:0
					Width:300
					Height:20
					Text:Показывать данные производительности
				Checkbox@CHECKUNSYNCED_CHECKBOX:
					X:0
					Y:30
					Width:300
					Height:20
					Text:Проверять синхронизацию на десинхронизированном коде
