## rules.yaml
briefing = LANDCOM 16 HQS.
    TOP SECRET.
    TO: FIELD COMMANDER A9
    
    INTELLIGENCE RECON SHOWS HEAVY
    SOVIET MOVEMENT IN YOUR AREA.
    NEARBY BRIDGES ARE KEY TO SOVIET
    ADVANCEMENT. DESTROY ALL BRIDGES
    ASAP. TANYA WILL ASSIST. KEEP HER
    ALIVE AT ALL COSTS.
    
    CONFIRMATION CODE 1612.
    
    TRANSMISSION ENDS.
