<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>OpenRA</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.0" />
		<PackageReference Include="Linguini.Bundle" Version="0.9.2" />
		<PackageReference Include="OpenRA-Eluant" Version="1.0.23" />
		<PackageReference Include="Mono.NAT" Version="3.0.4" />
		<PackageReference Include="SharpZipLib" Version="1.4.2" />
	</ItemGroup>
</Project>
