Container@LANGUAGE_PANEL:
	Logic: LanguageSettingsLogic
	Width: PARENT_WIDTH
	Height: PARENT_HEIGHT
	Children:
		ScrollPanel@SETTINGS_SCROLLPANEL:
			Width: PARENT_WIDTH
			Height: PARENT_HEIGHT
			CollapseHiddenChildren: True
			TopBottomSpacing: 5
			ItemSpacing: 10
			Children:
				Background@LANGUAGE_SECTION_HEADER:
					X: 5
					Width: PARENT_WIDTH - 24 - 10
					Height: 13
					Background: separator
					ClickThrough: True
					Children:
						Label@LABEL:
							Width: PARENT_WIDTH
							Height: PARENT_HEIGHT
							Font: TinyBold
							Align: Center
							Text: label-language-section-header
				Container@ROW:
					Width: PARENT_WIDTH - 24
					Height: 50
					Children:
						Container@LANGUAGE_DROPDOWN_CONTAINER:
							X: 10
							Width: PARENT_WIDTH / 2 - 20
							Children:
								Label@LANGUAGE_LABEL:
									Width: PARENT_WIDTH
									Height: 20
									Text: label-language-dropdown-container
								DropDownButton@LANGUAGE_DROPDOWN:
									Y: 25
									Width: PARENT_WIDTH
									Height: 25
									Font: Regular
				Container@ROW:
					Width: PARENT_WIDTH - 24
					Height: 30
					Children:
						Container@RESTART_REQUIRED_CONTAINER:
							X: 10
							Width: PARENT_WIDTH - 20
							Children:
								Label@LANGUAGE_RESTART_REQUIRED_DESC:
									Width: PARENT_WIDTH
									Height: 20
									Font: Tiny
									Text: label-restart-required-container-language-desc
									Align: Center
