Container@ADVANCED_PANEL:
	Logic: AdvancedSettingsLogic
	Width: PARENT_RIGHT
	Height: PARENT_BOTTOM
	Children:
		ScrollPanel@SETTINGS_SCROLLPANEL:
			Width: PARENT_RIGHT
			Height: PARENT_BOTTOM
			CollapseHiddenChildren: True
			TopBottomSpacing: 5
			ItemSpacing: 10
			Children:
				Background@NETWORK_SECTION_HEADER:
					X: 5
					Width: PARENT_RIGHT - 24 - 10
					Height: 13
					Background: separator
					ClickThrough: True
					Children:
						Label@LABEL:
							Width: PARENT_RIGHT
							Height: PARENT_BOTTOM
							Font: TinyBold
							Align: Center
							Text: label-network-section-header-label
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 20
					Children:
						Container@NAT_DISCOVERY_CONTAINER:
							X: 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@NAT_DISCOVERY:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: checkbox-nat-discovery-container-nat-discovery
						Container@FETCH_NEWS_CHECKBOX_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@FETCH_NEWS_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: checkbox-fetch-news-checkbox-container-fetch-news-checkbox
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 20
					Children:
						Container@PERFGRAPH_CHECKBOX_CONTAINER:
							X: 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@PERFGRAPH_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: checkbox-perfgraph-checkbox-container-perfgraph-checkbox
						Container@CHECK_VERSION_CHECKBOX_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@CHECK_VERSION_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: checkbox-check-version-checkbox-container-check-version-checkbox
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 50
					Children:
						Container@PERFTEXT_CHECKBOX_CONTAINER:
							X: 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@PERFTEXT_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: checkbox-perftext-checkbox-container-perftext-checkbox
						Container@SENDSYSINFO_CHECKBOX_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@SENDSYSINFO_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: checkbox-sendsysinfo-checkbox-container-sendsysinfo-checkbox
								Label@SENDSYSINFO_DESC:
									Y: 15
									Width: PARENT_RIGHT
									Height: 30
									Font: Tiny
									WordWrap: True
									Text: label-sendsysinfo-checkbox-container-sendsysinfo-desc
				Container@SPACER:
				Background@DEBUG_SECTION_HEADER:
					X: 5
					Width: PARENT_RIGHT - 24 - 10
					Height: 13
					Background: separator
					ClickThrough: True
					Children:
						Label@LABEL:
							Width: PARENT_RIGHT
							Height: PARENT_BOTTOM
							Font: TinyBold
							Align: Center
							Text: label-debug-section-header-label
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 40
					Children:
						Container@DEBUG_HIDDEN_CONTAINER:
							X: 10
							Width: PARENT_RIGHT - 10
							Children:
								Label@A:
									Width: PARENT_RIGHT
									Height: 20
									Text: label-debug-hidden-container-a
									Align: Center
								Label@B:
									Y: 20
									Width: PARENT_RIGHT
									Height: 20
									Text: label-debug-hidden-container-b
									Align: Center
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 20
					Children:
						Container@BOTDEBUG_CHECKBOX_CONTAINER:
							X: 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@BOTDEBUG_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: checkbox-botdebug-checkbox-container-botdebug-checkbox
						Container@CHECKBOTSYNC_CHECKBOX_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@CHECKBOTSYNC_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: checkbox-checkbotsync-checkbox-container-checkbotsync-checkbox
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 20
					Children:
						Container@LUADEBUG_CHECKBOX_CONTAINER:
							X: 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@LUADEBUG_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: checkbox-luadebug-checkbox-container-luadebug-checkbox
						Container@CHECKUNSYNCED_CHECKBOX_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@CHECKUNSYNCED_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: checkbox-checkunsynced-checkbox-container-checkunsynced-checkbox
				Container@ROW:
					Width: PARENT_RIGHT - 24
					Height: 20
					Children:
						Container@REPLAY_COMMANDS_CHECKBOX_CONTAINER:
							X: 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@REPLAY_COMMANDS_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: checkbox-replay-commands-checkbox-container-replay-commands-checkbox
						Container@PERFLOGGING_CHECKBOX_CONTAINER:
							X: PARENT_RIGHT / 2 + 10
							Width: PARENT_RIGHT / 2 - 20
							Children:
								Checkbox@PERFLOGGING_CHECKBOX:
									Width: PARENT_RIGHT
									Height: 20
									Font: Regular
									Text: checkbox-perflogging-checkbox-container-perflogging-checkbox

